#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# An extruded mesh around cylinder
(cd cylinderMesh && ./Allrun.pre)

# The background mesh
(cd cylinderAndBackground && ./Allrun $*)

#------------------------------------------------------------------------------
