#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam postProcessing constant/polyMesh/boundary
\rm -rf system/cellsToSmoothSubset

# Restore the stored case format
solids4Foam::restoreCaseFormat .
