#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf case.foam contact history
\rm -rf system/*Subset

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
