#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
m4 constant/polyMesh/blockMeshDict.neckingBar.m4 > constant/polyMesh/blockMeshDict
runApplication blockMesh

# Run solver
runApplication solids4Foam
#runApplication decomposePar -force
#runParallel solidFoam 8
#runApplication reconstructPar