#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
mkdir constant/polyMesh
m4 system/blockMeshDict.uniaxialRod.m4 > constant/polyMesh/blockMeshDict
solids4Foam::runApplication blockMesh

# Run solver
solids4Foam::runApplication solids4Foam
