#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

wclean lib src

cleanCase
\rm -f constant/polyMesh/boundary case.foam
\rm -rf system/*Subset constant/faMesh/faBoundary constant/faMesh/faceLabels

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
