#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

solids4Foam::caseDoesNotRunWithOpenFOAMOrg
solids4Foam::caseDoesNotRunWithFoamExtend

if [[ "${WM_PROJECT_VERSION#v}" -lt 2412 ]]
then
    echo
    echo "OpenFOAM-v2412 or a newer version is required for this case"
    echo
    exit 0
fi

# Create volume mesh
solids4Foam::runApplication blockMesh

# Create finite area mesh
solids4Foam::runApplication makeFaMesh

# Run solver
solids4Foam::runApplication solids4Foam

