#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

#solids4Foam::caseOnlyRunsWithFoamExtend

# Create the mesh
if [[ $WM_PROJECT == "foam" ]]
then
m4 -P constant/solid/blockMeshDict.m4 > constant/solid/polyMesh/blockMeshDict
m4 -P constant/fluid/blockMeshDict.m4 > constant/fluid/polyMesh/blockMeshDict
else
m4 -P constant/solid/blockMeshDict.m4 > system/solid/blockMeshDict
m4 -P constant/fluid/blockMeshDict.m4 > system/fluid/blockMeshDict
fi

solids4Foam::runApplication -s solid blockMesh -region solid
solids4Foam::runApplication -s fluid blockMesh -region fluid

# Run the solver
solids4Foam::runApplication solids4Foam


# ----------------------------------------------------------------- end-of-file

