#!/bin/bash

. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"
source solids4FoamScripts.sh

cleanCase
rm -rf 0.tmp gmsh/*.msh
solids4Foam::restoreCaseFormat .

for file in constant/solidProperties.segregated \
            system/fvSolution.segregated
do
    ln -vnsf "${file##*/}" "${file%.*}"
done
