#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -f constant/polyMesh/boundary case.foam
\rm -rf system/*Subset

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
