#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam history normalContact_*.txt frictionContact_*.txt

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
