#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create the mesh
runApplication blockMesh

# Run solver
runApplication pimpleFoam

# Remove empty time directories created by preCICE
solids4Foam::removeEmptyDirs
