#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cp constant/polyMesh/blockMeshDict system/
cleanCase
mkdir constant/polyMesh ; mv -f system/blockMeshDict constant/polyMesh/
\cp 0/alpha1.org 0/alpha1
\rm -f constant/polyMesh/boundary case.foam
