/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | foam-extend: Open Source CFD
   \\    /   O peration     |
    \\  /    A nd           | For copyright notice see file Copyright
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

Description
    Function that creates and writes differential stress fields given a stress
    tensor.

    One scalar fields is created: sigmaDiff
    sigmaDiff is the difference between the most positive/tensile principal stress and the
    most negative/compressive principal stress.

Author
    Scott Levie, Philip Cardiff, UCD.

\*---------------------------------------------------------------------------*/

#ifndef differentialStressFields_H
#define differentialStressFields_H

#include "volFields.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{
    // Set differential stress
    void calculateEigenValues(
        const symmTensor &sigma,
        scalar &sigmaDiff);

    // Calculate and write differential stress values
    void writedifferentialStressFields(const volSymmTensorField &sigma);

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
