#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
rm -f constant/polyMesh/boundary
cp 0/T.org 0/T

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
