#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cleanTimeDirectories
\rm -f constant/polyMesh/boundary case.foam
\rm -rf processor*
\rm -f *.eps
\rm -rf history
\rm -rf VTK
\rm -rf forces
