#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [[ $WM_PROJECT != "foam" ]]
then
    echo; echo "This case currently only runs in foam-extend"; echo
    exit 0
fi

runApplication fluentMeshToFoam cylinderInChannel.msh
runApplication changeDictionary
runApplication solids4Foam
