#!/bin/sh

# Clean ThirdParty
(cd ThirdParty && ./Allwclean)

# Clean libraries
(cd src && ./Allwclean)

# Clean applications
(cd applications && ./Allwclean)

# Clean all tutorials
(cd tutorials && ./Allclean)
