#!/bin/sh

(cd ThirdParty && \rm -rf eigen3)

wclean lib src/blockCoupledSolids4FoamTools
wclean lib src/solids4FoamModels

wclean applications/utilities/addPatch
wclean applications/utilities/addTinyPatch
wclean applications/utilities/flattenPatch
wclean applications/utilities/projectPatchToSphere
wclean applications/utilities/surfaceTractions
wclean applications/utilities/volPointInterpolate
wclean applications/utilities/mergeSubMeshes
wclean applications/utilities/smoothMesh

wclean applications/solvers/solids4Foam
wclean all applications/solvers
wclean all applications/utilities
