#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication fluentMeshToFoam CylinderInChannel.msh
runApplication changeDictionary
#runApplication solids4Foam
