#!/bin/bash
set -Eeuo pipefail
IFS=$'\n\t'

export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH:-}"
: "${FOAM_LD_LIBRARY_PATH:=}"
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"
source solids4FoamScripts.sh

cleanCase
\rm -rf constant/polyMesh/boundary case.foam postProcessing

# Restore the default (linearGeometry) case files
cp -a caseOptions/linearGeometry/. .

# Restore the stored case format
solids4Foam::restoreCaseFormat .
