#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf constant/polyMesh case.foam history 0/polyMesh 0/cellToRegion
\rm -rf 0/D[x,y,z] deformedTriSurfaces
