#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .



# Create cylinder mesh
runApplication cartesianMesh

# Scale the geometry to metres
echo "Running transformPoints"
transformPoints -scale "(0.001 0.001 0.001)" >& log.transformPoints

# Create patches
runApplication autoPatch 45 -overwrite
runApplication createPatch -overwrite

# Run the solver
runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

