#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

# Create cylinder mesh
runApplication cartesianMesh

# Scale the geometry to metres
echo "Running transformPoints"
transformPoints -scale "(0.001 0.001 0.001)" >& log.transformPoints

# Create patches
runApplication autoPatch 45 -overwrite
runApplication createPatch -overwrite

# Run the solver
runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

