#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

solids4Foam::caseOnlyRunsWithFoamExtend

# Create cylinder mesh
if ! command -v cartesianMesh &> /dev/null
then
    echo
    echo "cartesianMesh command not found, which is required for this case"
    echo
    exit 0
fi
solids4Foam::runApplication cartesianMesh

# Scale the geometry to metres
echo "Running transformPoints"
transformPoints -scale "(0.001 0.001 0.001)" >& log.transformPoints

# Create patches
solids4Foam::runApplication autoPatch 45 -overwrite
solids4Foam::runApplication createPatch -overwrite

# Run solver
solids4Foam::runApplication solids4Foam


