#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Run solver
#runApplication solids4Foam
solids4Foam | grep -v 'Both matrices are symmetric: inserting only upper triangle' 2>&1 | tee log.solids4Foam
