#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

[ -f constant/polyMesh/blockMeshDict ] && \cp constant/polyMesh/blockMeshDict system/blockMeshDict
cleanCase
[ -f system/blockMeshDict ] && mkdir constant/polyMesh && \cp system/blockMeshDict constant/polyMesh/blockMeshDict
\rm -rf constant/polyMesh/boundary case.foam postProcessing system/*Subset energies.dat

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
