#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

# Create the mesh
runApplication blockMesh

# Run the solver
runApplication $application

# ----------------------------------------------------------------- end-of-file

