#!/bin/bash

# This case currently gives errors with OpenFOAM.org
if [[ "${WM_PROJECT}" != "foam"* ]]
then
    if [[ "${WM_PROJECT_VERSION}" != *"v"* ]]
    then
        echo; echo "Skipping this case as it does not currently run with OpenFOAM.org"
        echo
        exit 0
    fi
fi

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
BLOCK_MESH_DICT_DIR=$(solids4Foam::blockMeshDictDir)
mkdir -p "${BLOCK_MESH_DICT_DIR}"
m4 system/blockMeshDict.cylinder.m4 > "${BLOCK_MESH_DICT_DIR}"/blockMeshDict
solids4Foam::runApplication blockMesh

if [[ $WM_PROJECT != "foam" ]]
then
    # Axis edges must be manually removed
    solids4Foam::runApplication collapseEdges -overwrite
fi

# Run solver
solids4Foam::runApplication solids4Foam
