#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .


# Create the mesh
m4 constant/polyMesh/blockMeshDict.cylinder.m4 > constant/polyMesh/blockMeshDict
runApplication blockMesh

# Run the solver in serial
runApplication solids4Foam

# Run the solver in parallel
#runApplication decomposePar
#runParallel solidFoam 8
#runApplication reconstructPar
