#!/bin/bash
set -Eeuo pipefail
IFS=$'\n\t'

# -------------------------------------------------------------------------
# solids4Foam Allrun script
# Allows selection of solution approach:
#   pressureDisplacementCompressible [coarse|medium]
#   pressureDisplacementIncompressible (default) [coarse|medium|poly]
# -------------------------------------------------------------------------

usage() {
cat <<'EOF'
Usage:
  ./Allrun [approach] [mesh]

Where [approach] is one of:
  pressureDisplacementCompressible
  pressureDisplacementIncompressible   (default)

The optional [mesh] argument selects:
  coarse                               (default)
  medium
  poly                                 (incompressible only)

Examples:
  ./Allrun
  ./Allrun pressureDisplacementCompressible medium
  ./Allrun pressureDisplacementIncompressible poly
EOF
}

# -------------------------------------------------------------------------
# Environment setup
# -------------------------------------------------------------------------

export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH:-}"
: "${FOAM_LD_LIBRARY_PATH:=}"
: "${WM_PROJECT_DIR:?OpenFOAM environment not sourced}"
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
source solids4FoamScripts.sh

# -------------------------------------------------------------------------
# Parse approach
# -------------------------------------------------------------------------

if [[ "${1:-}" =~ ^(-h|--help)$ ]]; then
    usage
    exit 0
fi

APPROACH="${1:-pressureDisplacementIncompressible}"
ARG2="${2:-}"

case "${APPROACH}" in
    pressureDisplacementCompressible)
        solids4Foam::caseOnlyRunsWithFoamExtend
        MESH="${ARG2:-coarse}"
        case "${MESH}" in
            coarse|medium) ;;
            *)
                echo "Error: Unknown mesh '${MESH}' for ${APPROACH}"
                usage
                exit 1
                ;;
        esac
        ;;
    pressureDisplacementIncompressible)
        solids4Foam::caseOnlyRunsWithFoamExtend
        MESH="${ARG2:-coarse}"
        case "${MESH}" in
            coarse|medium|poly) ;;
            *)
                echo "Error: Unknown mesh '${MESH}' for ${APPROACH}"
                usage
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Error: Unknown approach '${APPROACH}'"
        usage
        exit 1
        ;;
esac

# -------------------------------------------------------------------------
# Functions
# -------------------------------------------------------------------------

copy_contents() {
    local src="$1"
    local dst="$2"

    mkdir -p "${dst}"
    cp -a "${src}/." "${dst}/"
}

reset_active_case() {
    rm -rf 0
    rm -rf constant/polyMesh

    rm -f constant/dynamicMeshDict
    rm -f constant/g
    rm -f constant/mechanicalProperties
    rm -f constant/physicsProperties
    rm -f constant/solidProperties
    rm -f constant/timeVsPressure
    rm -f constant/timeVsTraction

    rm -f system/controlDict
    rm -f system/createPatchDict
    rm -f system/decomposeParDict
    rm -f system/fvSchemes
    rm -f system/fvSolution
    rm -f system/sampleDict

    rm -f postProcessing.gplt
}

select_pressure_displacement_case() {
    local material="$1"

    echo "Using ${APPROACH} approach with ${MESH} mesh"

    reset_active_case

    copy_contents caseOptions/pressureDisplacement/common/0 0
    copy_contents caseOptions/pressureDisplacement/common/constant constant
    copy_contents caseOptions/pressureDisplacement/common/system system
    copy_contents "caseOptions/pressureDisplacement/${material}/constant" constant

    if [[ "${MESH}" == "poly" ]]; then
        copy_contents caseOptions/pressureDisplacement/poly/constant constant
        copy_contents caseOptions/pressureDisplacement/poly/system system
    else
        copy_contents caseOptions/pressureDisplacement/hex/common/constant constant
        copy_contents caseOptions/pressureDisplacement/hex/common/system system
        copy_contents "caseOptions/pressureDisplacement/hex/${MESH}/constant" constant
        cp -a caseOptions/pressureDisplacement/hex/common/postProcessing.gplt .
    fi
}

select_approach() {
    case "${APPROACH}" in
        pressureDisplacementCompressible)
            select_pressure_displacement_case compressible
            ;;
        pressureDisplacementIncompressible)
            select_pressure_displacement_case incompressible
            ;;
    esac
}

# -------------------------------------------------------------------------
# Main workflow
# -------------------------------------------------------------------------

select_approach

echo
echo "Compiling libraries..."
(cd src && bash ./Allwmake -s)

solids4Foam::convertCaseFormat .

if [[ "${MESH}" != "poly" ]]; then
    echo
    solids4Foam::runApplication blockMesh
fi

solids4Foam::runApplication solids4Foam
