#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam history
\rm -rf system/*Subset probe energies.dat
