#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

echo
echo "Cleaning applications"
echo

wclean all solvers
wclean all utilities

#------------------------------------------------------------------------------
