#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

wmake all solvers
wmake all scripts

if [ "$WM_PROJECT" = "foam" ]
then
    wmake all utilities
else
    echo "utilities currently not compiled for this version"
fi
