#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

wclean src

cleanCase

rm -r 0

rm -r postProcessing history
rm -r logs

rm *.png
rm *.dat

# Remove the regression test cases too with ./Allclean all
if [ "${1:-}" = "all" ]
then
    rm -rf regressionTests
fi
