#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0
rm -rf postProcessing
rm -rf 'history'

rm -f *.log
rm -f *.foam
rm -f *.eps
rm -f *.dat
rm -f *.png
