#!/bin/bash

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

solids4Foam::caseOnlyRunsWithFoamExtend

set -e

# reset
rm -rf 0
cp -rf 0.orig 0

# paraview file
touch case.foam


# mesh
runApplication blockMesh

# Run solver
if [[ "$1" == "parallel" ]]
then
    runApplication decomposePar
    solids4Foam::runParallel solids4Foam
    runApplication reconstructPar
else
    runApplication solids4Foam
fi

# Plot tip displacement history
if command -v gnuplot &> /dev/null
then
    echo "Generating tipPointDisplacement.png using gnuplot"
    gnuplot tipPointDisplacement.gplt &> /dev/null
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
