#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones* 0/polyMesh
\rm -rf VTK case.foam history 0/pointMotion