#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

m4 constant/polyMesh/blockMeshDict.hotSphere.m4 \
    > constant/polyMesh/blockMeshDict
runApplication blockMesh

echo "Running projectPatchToSphere on inside patch"
projectPatchToSphere inside "(0 0 0)" 0.19 -overwrite \
    >& log.projectPatchToSphere.inside

echo "Running projectPatchToSphere on outside patch"
projectPatchToSphere outside "(0 0 0)" 0.2 -overwrite \
    >& log.projectPatchToSphere.outside

runApplication solidFoam