#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
runApplication blockMesh

# Run solver
if [[ "${1}" -gt 1 ]]
then
    # Number of cores passed as an argument
    runApplication decomposePar
    runParallel solids4Foam "${1}"
    runApplication reconstructPar
else
    # Case runs in serial if no argument is passed or if the argument is 1
    runApplication solids4Foam
fi
