#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
foamCleanPolyMesh -region fluid
foamCleanPolyMesh -region solid

rm -rf constant/polyMesh constant/triSurface system/meshDict \
    case.foam postProcessing dynamicCode

# Restore the stored case format
solids4Foam::restoreCaseFormat .
