#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

if (( "${WM_PROJECT_VERSION#v}" > 2012 ))
then
    echo; echo "This case currently does not run with this OpenFOAM verion";
    echo
    exit 0
fi

# Create meshes
solids4Foam::runApplication -s solid blockMesh -region solid
solids4Foam::runApplication -s fluid blockMesh -region fluid

# Set water volume fraction field (alpha) in the fluid
cp 0/fluid/alpha1.org 0/fluid/alpha1
(cd 0/fluid && ln -s alpha1 alpha.water)
solids4Foam::runApplication setFields -region fluid

# Run solver
solids4Foam::runApplication solids4Foam

# Create plots
if command -v gnuplot &> /dev/null
then
    echo "Generating plot"
    gnuplot -p plot.gnuplot &> /dev/null
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
