#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Create faceZones for solidContact boundaries
runApplication setSet -batch batch.setSet
runApplication setsToZones -noFlipMap

# Run solver
runApplication solidFoam
#runApplication decomposePar
#runParallel solidFoam 8
#runApplication reconstructPar
