#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -f constant/polyMesh/boundary case.foam
\rm -rf system/*Subset constant/*Subset VTK postProcessing/
\rm -rf *.png 0/cellToRegion

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .

if [[ "${WM_PROJECT}" == "OpenFOAM" ]]
then
    # Convert the new keywords, `point`, and `normal`, back to the old ones
    # still used in foam-extend: `basePoint` and `normalVector`
    sed -i -E 's/\bpoint\b/basePoint/' system/mirrorMeshDict
    sed -i -E 's/\b(normal)\b/\1Vector/' system/mirrorMeshDict
fi
