#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -f constant/polyMesh/boundary case.foam 
\rm -rf system/*Subset constant/*Subset VTK postProcessing/
\rm -rf *.png

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .

