#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication fluentMeshToFoam cylinderRotation.msh
runApplication changeDictionary

# Run solver
runApplication solids4Foam