#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -rf constant/polyMesh/boundary case.foam system/*Subset postProcessing

# Restore the stored case format
solids4Foam::restoreCaseFormat .
