#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Currently only checked with OpenFOAM-v2012
if [[ "${WM_PROJECT}" != "OpenFOAM" || "${WM_PROJECT_VERSION}" != "v2012" ]]
then
    echo; echo "This case currently only runs in OpenFOAM-v2012"; echo
    exit 0
fi

# Start fluid in background
echo; echo "Starting the fluid"
(cd fluid-openfoam && ./Allrun &> log.Allrun &)

# Start fluid in background
echo; echo "Starting the solid"
(cd solid-openfoam && ./Allrun &> log.Allrun &)

# Wait for fluid and solid to finish
echo; echo "Waiting for the fluid and solid to finish"
wait
echo; echo "done"; echo
