#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cleanCase fluid
cleanCase solid
foamClearPolyMesh -region fluid
foamClearPolyMesh -region solid
\rm -rf history constant/solid/polyMesh/boundary
\rm -rf constant/solid/polyMesh/[c-z]*
\rm -rf case.foam
\rm 0/fluid/alpha1
