#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create meshes
runApplication -l log.blockMesh.solid blockMesh -region solid
runApplication -l log.blockMesh.fluid blockMesh -region fluid

# Set water volume fraction field (alpha) in the fluid
# Note: setField does not have a '-region' option so we will use a work-around
# runApplication setFields -region fluid
\mv constant/fluid/polyMesh constant/
\mv system/fluid/setFieldsDict system/
\cp 0/fluid/alpha1.org 0/alpha1
runApplication setFields
\mv constant/polyMesh constant/fluid/
\mv system/setFieldsDict system/fluid/
\mv 0/alpha1 0/fluid/alpha1

if [[ "$1" == "parallel" ]]; then
    # Run parallel
    runApplication -l log.decomposePar.fluid decomposePar -region fluid
    runApplication -l log.decomposePar.solid decomposePar -region solid
    runParallel solids4Foam 4
    runApplication -l log.reconstructPar.fluid reconstructPar -region fluid
    runApplication -l log.reconstructPar.solid reconstructPar -region solid
else
    # Run serial
    runApplication solids4Foam
fi

# ----------------------------------------------------------------- end-of-file

