#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

wclean lib src

cleanCase
rm -rf constant/polyMesh/boundary VTK case.foam postProcessing 0/analytical* *.png

# Restore the stored case format
solids4Foam::restoreCaseFormat .
