#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

wclean lib src

[ -f constant/polyMesh/blockMeshDict ] && cp constant/polyMesh/blockMeshDict system/
cleanCase
[ -f system/blockMeshDict ] && mkdir -p constant/polyMesh && cp system/blockMeshDict constant/polyMesh/

\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones* sphericalCavity.msh
\rm -rf VTK case.foam postProcessing constant/polyMesh/boundary* *.obj

# Link files back to default solid model settings
for file in $(find ./constant ./system -name '*.petscSnes')
do
    ln -vnsf ${file##*/} ${file%.*}
done
