#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones* sphericalCavity.msh
\rm -rf VTK case.foam postProcessing constant/polyMesh/boundary* *.obj
