#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
rm -rf constant/polyMesh flowRate.pdf
