#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/RunFunctions

set -e

# reset
rm -rf 0
cp -rf 0.orig 0

# paraview file
touch case.foam


# mesh
runApplication blockMesh

#before running the case, run blockMesh command in openfoam2206 or openfoam2306
# run
runApplication solids4Foam
