#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
cleanCase fluid
cleanCase solid
(cd constant/solid/polyMesh && find . ! -name 'blockMeshDict' -type f -exec rm -f {} +)
(cd constant/fluid/polyMesh && find . ! -name 'blockMeshDict' -type f -exec rm -f {} +)
rm -rf case.foam residuals force.pdf deflection.pdf postProcessing

# Restore the stored case format
solids4Foam::restoreCaseFormat .
