#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

[ -f constant/polyMesh/blockMeshDict ] && cp constant/polyMesh/blockMeshDict system/
cleanCase
[ -f system/blockMeshDict ] && mkdir constant/polyMesh && cp system/blockMeshDict constant/polyMesh/
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam postProcessing

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
