#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Case only runs with some versions of OpenFOAM/FOAM
if [[ $WM_PROJECT = "foam" ]]
then
    echo; echo "FOAM EXTEND loaded: skipping case"; echo
    exit 0
fi

cleanCase
cleanCase fluid
cleanCase solid
\rm -rf history
\rm -rf constant/solid/polyMesh/boundary
\rm -rf constant/solid/polyMesh/[c-z]*
\rm -rf case.foam residuals
foamCleanPolyMesh -region fluid
foamCleanPolyMesh -region solid
