#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase

\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam postProcessing constant/polyMesh/boundary*

# Restore the stored case format
solids4Foam::restoreCaseFormat .

# Link files back to default solid model settings
for file in $(find ./0 ./constant ./system \( -type f -o -type l \) -name '*.petscSnes')
do
    ln -vnsf ${file##*/} ${file%.*}
done

# Link the OpenFOAM mesh dictionary back to the default location
\rm -f constant/polyMesh/blockMeshDict system/blockMeshDict
ln -vnsf blockMeshDict.openfoam system/blockMeshDict
