#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
rm -rf constant/polyMesh/boundary VTK case.foam history system/*Subset

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
