#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
rm -rf constant/polyMesh/boundary VTK case.foam postProcessing system/*Subset

# Restore the stored case format
solids4Foam::restoreCaseFormat .

# Fix for symmetry type: the temperature field time directories are not
# restored by solids4Foam::restoreCaseFormat, which only checks the 0 directory
echo "Replacing symmetryPlane with symmetry for T files in hotCylinderTemperatureField"
find hotCylinderTemperatureField -name T | xargs sed -i 's|symmetryPlane;|symmetry;|g'
