#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create the mesh
solids4Foam::runApplication blockMesh

# Create cellZones for materials
solids4Foam::runApplication setSet -batch batch.setSet
solids4Foam::runApplication setsToZones

# Fix for symmetry type
if [[ $WM_PROJECT != "foam" ]]
then
    echo "Replacing symmetryPlane with symmetry for T files in hotCylinderTemperatureField"
    find hotCylinderTemperatureField -name T | xargs sed -i 's\symmetryPlane\symmetry\g'
fi

# Run the solver
solids4Foam::runApplication solids4Foam
