#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
foamClearPolyMesh -region solid
\rm -rf 0/fluid constant/fluid system/fluid
\rm -rf history
\rm -f constant/polyMesh/boundary
\rm -f constant/solid/polyMesh/boundary
\rm -rf constant/solid/polyMesh/[c-z]*
\rm -f *.ps
\rm -f *.pdf case.foam
