#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
cleanCase fluid
cleanCase solid
rm -rf case.foam residuals 0/fluid constant/fluid system/fluid

# Restore the stored case format
solids4Foam::restoreCaseFormat .
