#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#
# First run the fluid case to completion
#

# Create fluid mesh
runApplication -l log.blockMesh.fluid blockMesh

# Run fluid solver
runApplication icoFoam


#
# Then run the solid case to completion, using the fluid interface forces
#

# Prepare the solid mesh
runApplication -l log.blockMesh.solid blockMesh -region solid

# Create links as the solid solver expects the fluid to be a sub-region
echo "Creating links to the fluid results"
\ln -s ../constant constant/fluid
\ln -s ../system system/fluid
find . -type d -name "[0-9]*" | while read i; do \ln -v -s ../$i $i/fluid ; done

# Run the solid solver
runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file
