#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#
# First run the fluid case to completion
#

if [[ $WM_PROJECT == "foam" ]]
then
    # Create fluid mesh
    runApplication -l log.blockMesh.fluid blockMesh

    # Run fluid solver
    runApplication icoFoam
else
    # Create fluid mesh
    runApplication -s fluid blockMesh

    # Run fluid solver
    icoFoam -noFunctionObjects &> log.icoFoam
fi


#
# Then run the solid case to completion, using the fluid interface forces
#

# Prepare the solid mesh
if [[ $WM_PROJECT == "foam" ]]
then
    runApplication -l log.blockMesh.solid blockMesh -region solid
else
    runApplication -s solid blockMesh -region solid
fi

# Create links as the solid solver expects the fluid to be a sub-region
echo "Creating links to the fluid results"
\ln -s ../constant constant/fluid
\ln -s ../system system/fluid
find . -type d -name "[0-9]*" | while read i; do \ln -v -s ../$i $i/fluid ; done

# Run the solid solver
if [[ $WM_PROJECT == "foam" ]]
then
    runApplication solids4Foam
else
    solids4Foam -noFunctionObjects &> log.solids4Foam
fi

# ----------------------------------------------------------------- end-of-file
