#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase

rm -r 0
rm -r postProcessing history
rm -r logs

rm *.eps
rm *.dat
rm *.foam
