#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
if [[ $WM_PROJECT = "foam" ]]; then
    foamClearPolyMesh -region fluid
    foamClearPolyMesh -region solid
elif [[ $WM_PROJECT_VERSION == v* ]]; then
    foamCleanPolyMesh -region fluid
    foamCleanPolyMesh -region solid
fi

rm -rf case.foam postProcessing residuals
rm -rf radialDisplacement.pdf fsiConvergence.pdf axialDisplacement.pdf

# Restore the stored case format
solids4Foam::restoreCaseFormat .

# Check fvSolution for foundation version
if [[ $WM_PROJECT = "OpenFOAM" ]] && [[ $WM_PROJECT_VERSION != *"v"* ]]
then
    if [[ -f "${CASE_DIR}"/system/fluid/fvSolution ]]
    then
        echo "OpenFOAM.org specific: replacing 'residualControl' with"
        echo " 'outerCorrectorResidualControl' in system/fluid/fvSolution"
        sed -i "s/outerCorrectorResidualControl/residualControl/g" "${CASE_DIR}"/system/fluid/fvSolution
    fi
fi

# Link files back to default with pimpleFluid
for file in $(find ./0 ./constant ./system -name '*.robin')
do
    ln -vnsf ${file##*/} ${file%.*}
done
