#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
cleanCase fluid
cleanCase solid
rm -rf case.foam postProcessing

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .

# Link files back to default with pimpleFluid
for file in $(find ./0 ./constant ./system -name '*.pimpleFluid')
do 
    ln -vnsf ${file##*/} ${file%.*}
done
