#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

if [[ "${WM_PROJECT}" == "foam" ]]
then
    solids4Foam::runApplication -l log.blockMesh.solid blockMesh -region solid
    solids4Foam::runApplication -l log.blockMesh.fluid blockMesh -region fluid
else
    solids4Foam::runApplication -s solid blockMesh -region solid
    solids4Foam::runApplication -s fluid blockMesh -region fluid
fi

# Run solver
solids4Foam::runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

