#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
rm -rf processor* force.pdf case.foam constant/polyMesh

# Restore the stored case format
solids4Foam::restoreCaseFormat .
