#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Example usage:
# ./Allrun                 -> pimpleFluid + residualControl 1e-4
# ./Allrun newtonIcoFluid  -> newtonIcoFluid + PETSc Schur fieldsplit
#                           + hypre pressure block

# Parse arguments
SOLVER="pimpleFluid"
for arg in "$@"; do
    if [[ "$arg" == "newtonIcoFluid" ]]; then
        SOLVER="newtonIcoFluid"
    fi
done

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Select the fluid solver and fvSolution
cp -f "constant/fluidProperties.${SOLVER}" constant/fluidProperties
cp -f "system/fvSolution.${SOLVER}" system/fvSolution
if [[ "${SOLVER}" == "newtonIcoFluid" ]]; then
    echo "Using ${SOLVER} with PETSc Schur fieldsplit preconditioning"
else
    echo "Using ${SOLVER} with residualControl 1e-4"
fi

# Create the mesh
solids4Foam::runApplication fluentMeshToFoam cylinderInChannel.msh
solids4Foam::runApplication changeDictionary

# Run the solver
solids4Foam::runApplication solids4Foam

# Create plots
if command -v gnuplot &> /dev/null
then
    if [ $(find . -name force.dat | wc -l) -eq 1 ]
    then
        echo "Generating force.pdf using gnuplot"
        gnuplot force.gnuplot &> /dev/null \
            || echo "Could not generate force.pdf using gnuplot"
    fi
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
