#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [[ $WM_PROJECT != "foam" ]]
then
    echo; echo "This case currently only runs in foam-extend"; echo
    exit 0
fi

# Create the mesh
runApplication fluentMeshToFoam cylinderInChannel.msh
runApplication changeDictionary

# Run the solver
runApplication solids4Foam
