#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

if [[ "${WM_PROJECT}" == "foam" ]]
then
    # fluent3DMeshToFoam does not have a region option so we need to workaround
    # it
    mkdir -p constant/solid/polyMesh
    runApplication -l log.fluent3DMeshToFoam.solid fluent3DMeshToFoam solid.msh
    \mv constant/polyMesh/* constant/solid/polyMesh/
    runApplication -l log.changeDictionary.solid changeDictionary -region solid

    mkdir -p constant/fluid/polyMesh
    runApplication fluent3DMeshToFoam fluid.msh
    \mv constant/polyMesh/* constant/fluid/polyMesh/
    runApplication changeDictionary -region fluid
else
    # fluent3DMeshToFoam does not have a region option so we need to workaround
    # it
    mkdir -p constant/solid/polyMesh
    runApplication -s solid fluent3DMeshToFoam solid.msh
    \mv constant/polyMesh/* constant/solid/polyMesh/
    echo "Running foamDictionary on solid"
    foamDictionary constant/solid/polyMesh/boundary -entry entry0.symmetry.type \
		   -set symmetry &> log.foamDictionary.solid

    mkdir -p constant/fluid/polyMesh
    runApplication -s fluid fluent3DMeshToFoam fluid.msh
    \mv constant/polyMesh/* constant/fluid/polyMesh/
    echo "Running foamDictionary on fluid"
    foamDictionary constant/fluid/polyMesh/boundary -entry entry0.symmetry.type \
		   -set symmetry &> log.foamDictionary.fluid
fi

# Run solver
runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

