#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

if [[ "${WM_PROJECT}" == "foam" ]]
then
    # fluent3DMeshToFoam does not have a region option so we need to workaround
    # it
    mkdir constant/solid/polyMesh
    runApplication -l log.fluent3DMeshToFoam.solid fluent3DMeshToFoam solid.msh
    \mv constant/polyMesh/* constant/solid/polyMesh/
    runApplication -l log.changeDictionary.solid changeDictionary -region solid

    mkdir constant/fluid/polyMesh
    runApplication fluent3DMeshToFoam fluid.msh
    \mv constant/polyMesh/* constant/fluid/polyMesh/
    runApplication changeDictionary -region fluid

    runApplication solids4Foam
else
    # fluent3DMeshToFoam does not have a region option so we need to workaround
    # it
    mkdir constant/solid/polyMesh
    runApplication -s solid fluent3DMeshToFoam solid.msh
    \mv constant/polyMesh/* constant/solid/polyMesh/
    runApplication -s solid changeDictionary -region solid

    mkdir constant/fluid/polyMesh
    runApplication -s fluid fluent3DMeshToFoam fluid.msh
    \mv constant/polyMesh/* constant/fluid/polyMesh/
    runApplication -s fluid changeDictionary -region fluid

    solids4Foam -noFunctionObjects &> log.solids4Foam
fi

# ----------------------------------------------------------------- end-of-file

