#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir constant/solid/polyMesh
runApplication -l log.fluent3DMeshToFoam.solid fluent3DMeshToFoam solid.msh
\mv constant/polyMesh/* constant/solid/polyMesh/
runApplication -l log.changeDictionary.solid changeDictionary -region solid

mkdir constant/fluid/polyMesh
runApplication fluent3DMeshToFoam fluid.msh
\mv constant/polyMesh/* constant/fluid/polyMesh/
runApplication changeDictionary -region fluid

if [[ "$1" == "parallel" ]]; then
    # Run parallel
    runApplication -l log.decomposePar.fluid decomposePar -region fluid
    runApplication -l log.decomposePar.solid decomposePar -region solid
    runParallel solids4Foam 4
    runApplication -l log.reconstructPar.fluid reconstructPar -region fluid
    runApplication -l log.reconstructPar.solid reconstructPar -region solid
else
    # Run serial
    runApplication solids4Foam
fi

# ----------------------------------------------------------------- end-of-file

