#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf constant/polyMesh/boundary case.foam history
\rm -rf system/*Subset energies.dat

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
