#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
if [[ $WM_PROJECT = "foam" ]]; then
    foamClearPolyMesh -region fluid
    foamClearPolyMesh -region solid
elif [[ $WM_PROJECT_VERSION == v* ]]; then
    foamCleanPolyMesh -region fluid
    foamCleanPolyMesh -region solid
fi

rm -rf case.foam residuals

# Restore the stored case format
solids4Foam::restoreCaseFormat .
