#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -l log.blockMesh.solid blockMesh -region solid
runApplication -l log.setsToZones.solid setsToZones -region solid -noFlipMap

runApplication -l log.blockMesh.fluid blockMesh -region fluid
runApplication -l log.setsToZones.fluid setsToZones -region fluid -noFlipMap

# Run serial
runApplication solids4Foam

# Run parallel
#runApplication -l log.decomposePar.fluid decomposePar -region fluid
#runApplication -l log.decomposePar.solid decomposePar -region solid
#runParallel solids4Foam 4
#runApplication -l log.reconstructPar.fluid reconstructPar -region fluid
#runApplication -l log.reconstructPar.solid reconstructPar -region solid


# ----------------------------------------------------------------- end-of-file

