#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# The inlet uses an expression PatchFunction1, which is only available in
# OpenFOAM.com
solids4Foam::caseDoesNotRunWithFoamExtend
solids4Foam::caseDoesNotRunWithOpenFOAMOrg

if [[ "${WM_PROJECT_VERSION#v}" -lt 2012 ]]
then
    echo
    echo "OpenFOAM-v2012 or a newer version is required for this case"
    echo
    exit 0
fi

# PETSc is required for the solid solver
solids4Foam::requirePetscOrExitSilently

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create meshes
solids4Foam::runApplication -s solid blockMesh -region solid
solids4Foam::runApplication -s fluid blockMesh -region fluid

# Refine the fluid mesh above and around the roof
solids4Foam::runApplication -s fluid setSet -batch setSet.batch -region fluid
solids4Foam::runApplication -s fluid refineMesh -region fluid -overwrite

# Run solver
if [[ "$1" == "parallel" ]]; then
    # Run parallel
    solids4Foam::runApplication -s fluid decomposePar -region fluid
    solids4Foam::runApplication -s solid decomposePar -region solid
    solids4Foam::runParallel solids4Foam
    solids4Foam::runApplication -s fluid reconstructPar -region fluid
    solids4Foam::runApplication -s solid reconstructPar -region solid
else
    # Run serial
    solids4Foam::runApplication solids4Foam
fi

# Create plots
if command -v gnuplot &> /dev/null
then
    echo "Generating deflection.pdf using gnuplot"
    gnuplot deflection.gnuplot &> /dev/null
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
