#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
wclean setPoiseuilleFlow
if [[ $WM_PROJECT = "foam" ]]; then
    foamClearPolyMesh -region fluid
    foamClearPolyMesh -region solid
elif [[ $WM_PROJECT_VERSION == v* ]]; then
    foamCleanPolyMesh -region fluid
    foamCleanPolyMesh -region solid
fi

rm -rf case.foam residuals deflection.pdf postProcessing
rm -f constant/solid/solidProperties system/solid/fvSolution
rm -f constant/fsiProperties 0/fluid/U 0/fluid/p

# Restore the stored case format
solids4Foam::restoreCaseFormat .
