#!/bin/sh
#------------------------------------------------------------------------------
# License
#     This file is part of solids4foam, licensed under GNU General Public
#     License <http://www.gnu.org/licenses/>.
#
# Script
#     Allrun
#
# Description
#    Recursively run all cases in this directory and sub-directories.
#    Adapted from foam-extend-4.0 and OpenFOAM-v2012 tutorials/Alltest scripts.
#
#------------------------------------------------------------------------------
cd ${0%/*} || exit 1    # Run from this directory

#
# FUNCTION DEFINITIONS
#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# logReport <logfile>
# Extracts useful info from log file
logReport()
{
    caseName=`dirname $1 | sed s/"\(.*\)\.\/"/""/g`
    app=`echo $1 | sed s/"\(.*\)log\."/""/g`
    appAndCase="Application $app - case $caseName"

    fatalError=`grep "FOAM FATAL" $1`
    UxSS=`grep -E "Ux[:| ]*solution singularity" $1`
    UySS=`grep -E "Uy[:| ]*solution singularity" $1`
    UzSS=`grep -E "Uz[:| ]*solution singularity" $1`
    completed=`grep -E "^[\t ]*[eE]nd" $1`

    if [ "$fatalError" ]
    then
        echo "$appAndCase: ** FOAM FATAL ERROR **"
        return 1
    elif [ "$UxSS" -a "$UySS" -a "$UzSS" ]
    then
        echo "$appAndCase: ** Solution singularity **"
        return 1
    elif [ "$completed" ]
    then
        completionTime=`tail -10 $log | grep Execution | cut -d= -f2 | sed 's/^[ \t]*//'`
        if [ "$completionTime" ]
        then
            completionTime="in $completionTime"
        fi
        echo "$appAndCase: completed $completionTime"
        return 0
    else
        echo "$appAndCase: unconfirmed completion"
        return 1
    fi
}


# logReportDir <directory>
# Extracts useful info from all log files in a directory
logReportDir()
(
    [ -d $1 ] || return 0

    cd $1 || return 1

    logs=`find . -name "log.*"`
    [ -n "$logs" ] || return 0

    retVal=0

    for log in `echo $logs | xargs ls -rt`
    do
        logReport $log >> ../testLoopReport || retVal=1
    done
    echo "" >> ../testLoopReport

    return $retVal
)


#
# MAIN
#

# Recursively run all cases
if [[ $WM_PROJECT = "foam" ]]
then
    foamRunTutorials cases
else
    foamRunTutorials
fi


# Analyse all log files
rm -f testLoopReport && touch testLoopReport

retVal=0

for appDir in *
do
    logReportDir $appDir || retVal=1
done

find . -name "log.*" -exec cat {} \; >> logs

exit $retVal

#------------------------------------------------------------------------------
