#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -l log.blockMesh.solid blockMesh -region solid
runApplication -l log.setSet.solid setSet -region solid -batch setBatch.solid
runApplication -l log.setsToZones.solid setsToZones -region solid -noFlipMap

runApplication blockMesh
runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

runApplication fsiFoam

#runApplication -l log.decomposeParFsi.fluid decomposeParFsi
#runApplication -l log.decomposeParFsi.solid decomposeParFsi -region solid
#runParallel fsiFoam 4

# ----------------------------------------------------------------- end-of-file

