#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

solids4Foam::caseOnlyRunsWithFoamExtend

# Create the mesh
runApplication -l log.blockMesh.solid blockMesh -region solid
runApplication -l log.blockMesh.fluid blockMesh -region fluid

# Run the solver
runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

