#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# fvOptions are not implemented in the foam-extend pimpleFluid
solids4Foam::caseDoesNotRunWithFoamExtend

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create the mesh
solids4Foam::runApplication blockMesh

# Run the solver
solids4Foam::runApplication solids4Foam
