#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# In OpenFOAM.org, cleanCase removes constant/polyMesh entirely, which would
# delete the blockMeshDict stored there in this case and leave the case unable
# to re-run. Stash the blockMeshDict and restore it after cleanCase, as is done
# in the cooksMembrane tutorial.
[ -f constant/polyMesh/blockMeshDict ] && cp constant/polyMesh/blockMeshDict system/
cleanCase
[ -f system/blockMeshDict ] && mkdir -p constant/polyMesh \
    && mv system/blockMeshDict constant/polyMesh/

\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam postProcessing 0/DD

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
