#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [[ $WM_PROJECT != "foam" ]]
then
    echo; echo "This case currently only runs in foam-extend"; echo
    exit 0
fi

# Create the mesh
runApplication blockMesh

# Run the solver
runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

