#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

echo "optionalFixes/Allcheck"

# This script reports on files that require fixes in the OpenFOAM installation.
# Currently, only foam-extend-4.1 requires fixes.
# To skip these checks, set S4F_NO_FILE_FIXES=1, i.e.
#   export S4F_NO_FILE_FIXES=1
# To see the consequence of these fixes, visit solids4foam.github.io

# Function for the checking and reporting how to replace a file
# Arguments:
#   $1  - File name
#   $2  - Target path, without the file name and the slash at the end
#   $3  - Path to library to be re-built
#
checkAndReport()
{
    if [ -n "$S4F_NO_FILE_FIXES" ]
    then
        echo "The S4F_NO_FILE_FIXES variable is set so checks will not be performed"
    elif cmp --silent "./${1}" "${2}/${1}"
    then
        echo "'${1}' has already been replaced"
        return 0
    else
        echo
        echo "******** PLEASE FIX THIS ***********"
        echo "You should replace the file '${2}/${1}' with 'optionalFixes/${1}'"
        echo
        echo "You can do it by running the following commands:"
        echo "    cp optionalFixes/${1} ${2}/"
        echo "    wmake libso ${3}"
        echo "************************************"
        echo
        return 1
    fi
}


# Different checks required for each version of OpenFOAM/foam
result=0
if [ "$WM_PROJECT" = "foam" ]
then
    # This fixes the segmentation error that happens at the end of solver due to
    # a mesh object being freed twice
    checkAndReport \
        "meshObjectBase.H" \
        "$FOAM_SRC/foam/meshes/MeshObject" \
        "$FOAM_SRC/foam"
    if [ $? -ne 0 ]; then result=1; fi

    # This fixes segmentation errors related to point fields when mesh
    # topological changes occur
    checkAndReport \
        "pointBoundaryMesh.C" \
        "$FOAM_SRC/foam/meshes/pointMesh/pointBoundaryMesh" \
        "$FOAM_SRC/foam"
    if [ $? -ne 0 ]; then result=1; fi
    
    # This fixes consistent Rhie-Chow interpolation
    # for Euler scheme
    checkAndReport \
        "EulerDdtScheme.C" \
        "$FOAM_SRC/finiteVolume/finiteVolume/ddtSchemes/EulerDdtScheme" \
        "$FOAM_SRC/finiteVolume"
    if [ $? -ne 0 ]; then result=1; fi

    # Fix time index storage in the storeOldTimes function
    checkAndReport \
        "GeometricField.C" \
        "$FOAM_SRC/foam/fields/GeometricFields/GeometricField" \
        "$FOAM_SRC/foam"
    if [ $? -ne 0 ]; then result=1; fi
else
    echo "No fixes needed for this version of OpenFOAM"; echo
    exit 0;
fi

echo

# If files check fails, then print error below
if [ "$result" -ne 0 ]
then
    echo "******** PLEASE FIX THIS ***********"
    echo "Please replace the files above"
    echo "************************************"
    echo
    exit 1
fi
