#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
cleanCase fluid
cleanCase solid
rm -rf constant/fluid/polyMesh constant/solid/polyMesh
rm -rf case.foam deflection.pdf postProcessing

# Remove the regression test cases too with ./Allclean all
if [ "${1:-}" = "all" ]
then
    rm -rf regressionTests
fi
