#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create the mesh
runApplication fluentMeshToFoam plate.msh
runApplication changeDictionary

# Run the solver
runApplication solids4Foam
