#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -l log.blockMesh.solid blockMesh -region solid
runApplication -l log.blockMesh.fluid blockMesh -region fluid

# Run serial
runApplication solids4Foam

# Run parallel
#runApplication -l log.decomposePar.fluid decomposePar -region fluid
#runApplication -l log.decomposePar.solid decomposePar -region solid
#runParallel solids4Foam 3

# ----------------------------------------------------------------- end-of-file

