#!/bin/bash
set -Eeuo pipefail
IFS=$'\n\t'

# Source tutorial clean functions
export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH:-}"
: "${FOAM_LD_LIBRARY_PATH:=}"
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -rf 0
\rm -rf constant/polyMesh
\rm -rf case.foam postProcessing history logs system/*Subset constant/*Subset
\rm -rf analyticalSolution
\rm -f *.dat *.eps
\rm -f innerRadius.gplt postProcessing.gplt pressure.gplt solidEnergy.gplt

\rm -f constant/cellDecomposition
\rm -f constant/dynamicMeshDict
\rm -f constant/g
\rm -f constant/mechanicalProperties
\rm -f constant/physicsProperties
\rm -f constant/solidProperties
\rm -f constant/timeVsPressure

\rm -f system/controlDict
\rm -f system/decomposeParDict
\rm -f system/fvSchemes
\rm -f system/fvSolution
\rm -f system/sampleDict

mkdir -p 0 constant system
cp -a caseOptions/displacement/0/. 0/
cp -a caseOptions/displacement/constant/. constant/
cp -a caseOptions/displacement/system/. system/

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
