#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication solids4Foam
runApplication postProcess -func sample -latestTime

gnuplot plot.gnuplot

# ----------------------------------------------------------------- end-of-file

