#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Case does not run with OpenFOAM.org
solids4Foam::caseDoesNotRunWithOpenFOAMOrg

# "./Allrun parallel" runs in parallel, decomposed with
# system/decomposeParDict.interface, which puts the processor boundary on the
# material interface; "./Allrun parallel simple" uses
# system/decomposeParDict.simple, whose processor boundary cuts across it
PARALLEL=false
DECOMPOSITION="interface"
for arg in "$@"; do
    case "$arg" in
        parallel) PARALLEL=true ;;
        interface|simple) DECOMPOSITION="$arg" ;;
    esac
done

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
solids4Foam::runApplication blockMesh

# Create material cellZones
solids4Foam::runApplication setSet -batch batch.setSet
solids4Foam::runApplication setsToZones

# Run solver
if [[ "${PARALLEL}" == true ]]
then
    echo "Running in parallel with the ${DECOMPOSITION} decomposition"
    cp "system/decomposeParDict.${DECOMPOSITION}" system/decomposeParDict

    if [[ "${DECOMPOSITION}" == "interface" ]]
    then
        # Processor 0 for the inner material, processor 1 for the outer: every
        # cell is 1 except those listed in the inner cellSet, which is written
        # as a count, "(", one label per line, then ")"
        nCells=$(grep -o 'nCells:[ ]*[0-9]*' constant/polyMesh/owner \
            | grep -o '[0-9]*$')
        awk -v n="${nCells}" '
            BEGIN { for (i = 0; i < n; i++) proc[i] = 1 }
            /^\($/ { inList = 1; next }
            /^\)$/ { inList = 0; next }
            inList { proc[$1] = 0 }
            END {
                print "FoamFile"
                print "{"
                print "    version     2.0;"
                print "    format      ascii;"
                print "    class       labelList;"
                print "    object      cellDecomposition;"
                print "}"
                print n
                print "("
                for (i = 0; i < n; i++) print proc[i]
                print ")"
            }
        ' constant/polyMesh/sets/inner > constant/cellDecomposition
    fi

    solids4Foam::runApplication decomposePar
    solids4Foam::runParallel solids4Foam
    solids4Foam::runApplication reconstructPar
else
    solids4Foam::runApplication solids4Foam
fi

# Sample stress along lines
if [[ $WM_PROJECT = "foam" ]]
then
    solids4Foam::runApplication sample -latestTime
else
    solids4Foam::runApplication postProcess -func sample -latestTime
fi

# Create plots
if command -v gnuplot &> /dev/null
then
    echo "Generating sigmaR.png and sigmaTheta.png using gnuplot"
    gnuplot plot.gnuplot &> /dev/null
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
