#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
solids4Foam::runApplication blockMesh
solids4Foam::runApplication topoSet

# Run solver
solids4Foam::runApplication solids4Foam

# Create graphs
solids4Foam::runApplication postProcess -func sample -latestTime
gnuplot plot.gnuplot

# ----------------------------------------------------------------- end-of-file

