#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
if [[ $WM_PROJECT = "foam" ]]; then
    foamClearPolyMesh -region fluid
    foamClearPolyMesh -region solid
else
    foamCleanPolyMesh -region fluid
    foamCleanPolyMesh -region solid
fi
rm -rf case.foam residuals force.pdf deflection.pdf postProcessing

# Remove symlinks created by Allrun for monolithic/partitioned switching
find ./0 ./constant ./system -maxdepth 3 -type l -exec rm -f {} \; 2>/dev/null

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
