#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

if [[ "${WM_PROJECT}" == "foam" ]]
then
    runApplication -l log.blockMesh.solid blockMesh -region solid
    runApplication -l log.blockMesh.fluid blockMesh -region fluid

    if [[ "$1" == "parallel" ]]; then
        # Run parallel
        runApplication -l log.decomposePar.fluid decomposePar -region fluid
        runApplication -l log.decomposePar.solid decomposePar -region solid
        runParallel solids4Foam 4
        runApplication -l log.reconstructPar.fluid reconstructPar -region fluid
        runApplication -l log.reconstructPar.solid reconstructPar -region solid
    else
        # Run serial
        runApplication solids4Foam
    fi
else
    runApplication -s solid blockMesh -region solid
    runApplication -s fluid blockMesh -region fluid

    if [[ "$1" == "parallel" ]]; then
        # Run parallel
        runApplication -s fluid decomposePar -region fluid
        runApplication -s solid decomposePar -region solid
        mpirun -np 4 solids4Foam -parallel -noFunctionObjects &> log.solids4Foam
        runApplication -s fluid reconstructPar -region fluid
        runApplication -s solid reconstructPar -region solid
    else
        # Run serial
        runApplication solids4Foam
    fi
fi

# Create plots
if command -v gnuplot &> /dev/null
then
    echo "Generating deflection.pdf using gnuplot"
    gnuplot deflection.gnuplot &> /dev/null
    echo "Generating force.pdf using gnuplot"
    gnuplot force.gnuplot &> /dev/null
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
