#!/usr/bin/env python3
"""Run the opt-in ringAddedMass verification study in isolated case copies.

The ring starts undeformed with the velocity of its n = 2 (ovalling) mode and
vibrates freely. The driver measures the dry (in vacuo) and wet (fluid-loaded)
frequencies from the zero crossings of the ovalling displacement, and
compares the frequencies and the wet/dry ratio with the exact linear
solution in reference/ringAddedMass_verification_references.json.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import csv
import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve()
VERIFICATION = SCRIPT.parents[1]
TUTORIAL = VERIFICATION.parent
REFERENCE_FILE = (
    VERIFICATION / "reference" / "ringAddedMass_verification_references.json"
)
WORK_ROOT = VERIFICATION / "work"
OUTPUT_ROOT = VERIFICATION / "postProcessing"
SETTINGS_FILE = "verification_settings.json"
HISTORY_X = "postProcessing/0/solidPointDisplacement_pointDispX.dat"
HISTORY_Y = "postProcessing/0/solidPointDisplacement_pointDispY.dat"
RESIDUALS = "postProcessing/fsiResiduals.dat"


def fail(message: str) -> None:
    raise RuntimeError(message)


def replace_entry(path: Path, key: str, value: str) -> None:
    text = path.read_text()
    pattern = rf"^(\s*{re.escape(key)}\s+)[^;]+;"
    text, count = re.subn(pattern, rf"\g<1>{value};", text, flags=re.MULTILINE)
    if count != 1:
        fail(f"Expected one '{key}' entry in {path}, found {count}")
    path.write_text(text)


def is_time_directory(name: str) -> bool:
    try:
        float(name)
    except ValueError:
        return False
    return name != "0"


# ---------------------------------------------------------------------------
# Case preparation
# ---------------------------------------------------------------------------

def ignore_results(directory: str, names: list[str]) -> set[str]:
    """Skip run output and anything that is not part of the tutorial set-up,
    in particular time directories left by an earlier tutorial run."""
    ignored = set()
    for name in names:
        if (
            name in ("verification", "regressionTests", "postProcessing",
                     "dynamicCode", "case.foam")
            or name.startswith("processor")
            or name.startswith("log.")
            or name.endswith(".pdf")
            or is_time_directory(name)
        ):
            ignored.add(name)
        if name == "polyMesh" and Path(directory).name in ("fluid", "solid") \
                and Path(directory).parent.name == "constant":
            ignored.add(name)
    return ignored


def refine_mesh(path: Path, factor: int) -> None:
    """Multiply the in-plane block divisions, keeping the single axial cell."""
    text = path.read_text()

    def scale(match: re.Match[str]) -> str:
        counts = [int(value) for value in match.group(2).split()]
        if len(counts) != 3:
            fail(f"Unexpected block division tuple in {path}: {match.group(2)}")
        counts = [counts[0] * factor, counts[1] * factor, counts[2]]
        return match.group(1) + "(" + " ".join(str(v) for v in counts) + ")"

    text, count = re.subn(r"(hex\s+\([^)]*\)\s+)\(([^()]+)\)", scale, text)
    if count != 1:
        fail(f"Expected one block in {path}, found {count}")
    path.write_text(text)


def time_controls(control: Path, delta_t: float, n_steps: int) -> None:
    replace_entry(control, "deltaT", f"{delta_t:.12g}")
    replace_entry(control, "endTime", f"{n_steps * delta_t:.12g}")
    # Write the fields at the end only; the point displacements are written
    # every time step
    replace_entry(control, "writeInterval", str(n_steps))
    replace_entry(control, "timePrecision", "12")


DRY_ALLRUN = """#!/bin/bash

# Dry (in vacuo) ring generated by the ringAddedMass verification driver

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# PETSc is required for this case
solids4Foam::requirePetscOrExitSilently

# Check case version is correct
solids4Foam::convertCaseFormat .

solids4Foam::runApplication blockMesh
solids4Foam::runApplication solids4Foam
"""


def prepare_dry(case: Path, solid: str) -> None:
    """Assemble a solid-only case from the solid region of the tutorial."""
    source = case.parent / (case.name + ".source")
    if source.exists():
        shutil.rmtree(source)
    shutil.copytree(TUTORIAL, source, ignore=ignore_results)
    for sub in ("0", "constant", "system"):
        (case / sub).mkdir(parents=True)
    for name in ("D", "D_0", "D_0_0", "pointD"):
        shutil.copy(source / "0/solid" / name, case / "0" / name)
    for name in ("mechanicalProperties", "dynamicMeshDict", "g"):
        shutil.copy(source / "constant/solid" / name, case / "constant" / name)
    shutil.copy(source / f"constant/solid/solidProperties.{solid}",
                case / "constant/solidProperties")
    for name in ("fvSchemes", "fvSolution", "blockMeshDict", "decomposeParDict"):
        shutil.copy(source / "system/solid" / name, case / "system" / name)
    shutil.copy(source / "system/controlDict", case / "system/controlDict")
    physics = (source / "constant/physicsProperties").read_text()
    physics, count = re.subn(r"^type\s+fluidSolidInteraction;", "type    solid;",
                             physics, flags=re.MULTILINE)
    if count != 1:
        fail("Could not set the solid physics type")
    (case / "constant/physicsProperties").write_text(physics)
    (case / "Allrun").write_text(DRY_ALLRUN)
    (case / "Allrun").chmod(0o755)
    shutil.rmtree(source)


def case_name(spec: dict) -> str:
    parts = [spec["kind"]]
    if spec["kind"] == "wet":
        parts += [spec["level"], spec["coupling"]]
    parts += [spec["solid"], f"m{spec['factor']}", f"n{spec['steps']}",
              f"p{spec['periods']}"]
    return "_".join(parts)


def settings(spec: dict, reference: dict) -> dict:
    """Everything that defines a run, used to validate a reused case."""
    data = {k: v for k, v in spec.items() if k != "groups"}
    data["deltaT"] = spec["period"] / spec["steps"]
    data["nSteps"] = spec["steps"] * spec["periods"]
    data["material"] = reference["material"]
    data["geometry"] = reference["geometry"]
    data["fluid"] = reference["fluid"]
    if spec["kind"] == "wet":
        data["rhoFluid"] = reference["levels"][spec["level"]]["rhoFluid"]
    data["tutorialFiles"] = tutorial_signature()
    data["build"] = build_signature()
    return data


def build_signature() -> dict:
    """OpenFOAM version and the solids4foam executable and library, so that a
    run is not reused with a different or rebuilt solver."""
    signature = {key: os.environ.get(key, "")
                 for key in ("WM_PROJECT", "WM_PROJECT_VERSION", "WM_OPTIONS")}
    candidates = [shutil.which("solids4Foam")]
    libbin = os.environ.get("FOAM_USER_LIBBIN", "")
    if libbin:
        candidates += sorted(str(p) for p in Path(libbin).glob(
            "libsolids4FoamModels.*"))
    for candidate in candidates:
        if candidate:
            status = Path(candidate).stat()
            signature[candidate] = f"{status.st_size}:{status.st_mtime_ns}"
    return signature


_SIGNATURE: dict | None = None


def tutorial_signature() -> dict:
    """Content hashes of the tutorial files that define the runs."""
    global _SIGNATURE
    if _SIGNATURE is None:
        signature = {}
        for path in sorted(TUTORIAL.rglob("*")):
            relative = path.relative_to(TUTORIAL)
            top = relative.parts[0]
            # Only the files that define the runs
            if top not in ("0", "constant", "system", "Allrun") \
                    or "polyMesh" in relative.parts or path.is_dir():
                continue
            if path.is_symlink():
                signature[str(relative)] = "->" + str(path.readlink())
            else:
                signature[str(relative)] = hashlib.sha1(
                    path.read_bytes()).hexdigest()
        _SIGNATURE = signature
    return _SIGNATURE


def configure(case: Path, spec: dict, reference: dict) -> None:
    delta_t = spec["period"] / spec["steps"]
    n_steps = spec["steps"] * spec["periods"]
    if spec["kind"] == "dry":
        prepare_dry(case, spec["solid"])
        refine_mesh(case / "system/blockMeshDict", spec["factor"])
    else:
        shutil.copytree(TUTORIAL, case, symlinks=True, ignore=ignore_results)
        refine_mesh(case / "system/solid/blockMeshDict", spec["factor"])
        refine_mesh(case / "system/fluid/blockMeshDict", spec["factor"])
        rho = reference["levels"][spec["level"]]["rhoFluid"]
        replace_entry(case / "constant/fluid/transportProperties", "rho",
                      f"rho [1 -3 0 0 0 0 0] {rho:.12g}")
    time_controls(case / "system/controlDict", delta_t, n_steps)


def solver_completed(case: Path) -> bool:
    log = case / "log.solids4Foam"
    return log.is_file() and bool(
        re.search(r"^End\s*$", log.read_text(errors="replace"), re.MULTILINE)
    )


def run_case(spec: dict, reference: dict, reuse: bool) -> str:
    case = WORK_ROOT / spec["name"]
    wanted = settings(spec, reference)
    stored = case / SETTINGS_FILE
    if reuse and case.is_dir():
        previous = None
        if stored.is_file():
            try:
                previous = json.loads(stored.read_text())
            except json.JSONDecodeError:
                previous = None
        if previous == wanted and solver_completed(case):
            try:
                read_histories(case, spec)
                return f"{spec['name']}: reusing the completed run"
            except RuntimeError as error:
                print(f"{spec['name']}: not reused ({error})")
        else:
            print(f"{spec['name']}: cached run does not match the requested "
                  "settings or did not finish; running it again")
    if case.exists():
        shutil.rmtree(case)
    configure(case, spec, reference)
    stored.write_text(json.dumps(wanted, indent=2, sort_keys=True))

    command = ["./Allrun"]
    if spec["kind"] == "wet":
        command += [spec["coupling"], spec["solid"]]
    log = case / "log.Allverify"
    with log.open("w") as handle:
        result = subprocess.run(command, cwd=case, stdout=handle,
                                stderr=subprocess.STDOUT, text=True)
    solver_log = case / "log.solids4Foam"
    if not solver_log.is_file():
        fail(f"{spec['name']} did not run the solver; see {log}")
    text = solver_log.read_text(errors="replace")
    if re.search(r"FOAM FATAL|FOAM aborting", text):
        fail(f"{spec['name']} failed; see {solver_log}")
    if not re.search(r"^End\s*$", text, re.MULTILINE):
        fail(f"{spec['name']} did not run to completion; see {solver_log}")
    if result.returncode:
        # The tutorial Allrun only fails after the solver when plotting
        print(f"{spec['name']}: Allrun returned {result.returncode} after the "
              f"solver completed; see {log}")
    return f"{spec['name']}: completed"


# ---------------------------------------------------------------------------
# History analysis
# ---------------------------------------------------------------------------

def read_columns(path: Path, column: int) -> tuple[list[float], list[float]]:
    if not path.is_file():
        fail(f"Missing history {path}")
    times, values = [], []
    for line in path.read_text(errors="replace").splitlines():
        fields = line.split()
        if not fields or fields[0].startswith("#"):
            continue
        try:
            t, v = float(fields[0]), float(fields[column])
        except (ValueError, IndexError):
            fail(f"Malformed line in {path}: {line!r}")
        if not (math.isfinite(t) and math.isfinite(v)):
            fail(f"Non-finite value in {path}: {line!r}")
        if times and t <= times[-1]:
            fail(f"Non-increasing time in {path} at t = {t}")
        times.append(t)
        values.append(v)
    return times, values


def read_histories(case: Path, spec: dict) -> tuple[list[float], list[float]]:
    """Ovalling displacement (u_r(0) - u_r(pi/2))/2, which removes any
    breathing (n = 0) component; checks the history is complete."""
    tx, ux = read_columns(case / HISTORY_X, 1)
    ty, uy = read_columns(case / HISTORY_Y, 2)
    delta_t = spec["period"] / spec["steps"]
    n_steps = spec["steps"] * spec["periods"]
    end_time = n_steps * delta_t
    for times in (tx, ty):
        if len(times) < n_steps or abs(times[-1] - end_time) > 0.5 * delta_t:
            fail(f"Truncated history in {case}: {len(times)} samples up to "
                 f"t = {times[-1] if times else 'none'}, expected {n_steps} "
                 f"up to t = {end_time:.6g}")
    if tx != ty:
        fail(f"Mismatched history times in {case}")
    return tx, [0.5 * (a - b) for a, b in zip(ux, uy)]


def linear_fit(x: list[float], y: list[float]) -> tuple[float, float]:
    n = len(x)
    mean_x, mean_y = sum(x) / n, sum(y) / n
    sxx = sum((a - mean_x) ** 2 for a in x)
    sxy = sum((a - mean_x) * (b - mean_y) for a, b in zip(x, y))
    slope = sxy / sxx
    return slope, mean_y - slope * mean_x


def frequency_and_damping(times: list[float], values: list[float],
                          periods: int) -> dict:
    """Damped frequency from a straight-line fit to the zero-crossing times
    (the zero crossings of a damped sinusoid are exactly half a damped period
    apart), and the decay rate from the peaks."""
    crossings = []
    for i in range(len(values) - 1):
        a, b = values[i], values[i + 1]
        if a == 0.0 or a * b < 0.0:
            crossings.append(times[i] + a / (a - b) * (times[i + 1] - times[i]))
    # Skip the first crossing, which the start-up transient can perturb
    crossings = crossings[1:]
    expected = 2 * periods - 2
    if len(crossings) < expected:
        fail(f"Found {len(crossings)} zero crossings, expected at least "
             f"{expected}")
    half_period, _ = linear_fit(list(range(len(crossings))), crossings)
    omega = math.pi / half_period
    residual = max(
        abs(t - (crossings[0] + k * half_period)) for k, t in enumerate(crossings)
    )
    if residual > 0.1 * half_period:
        fail("Zero crossings are not evenly spaced; the response is not a "
             "single-mode vibration")

    peaks = []
    for i in range(1, len(values) - 1):
        y0, y1, y2 = abs(values[i - 1]), abs(values[i]), abs(values[i + 1])
        same_sign = values[i] * values[i - 1] > 0 and values[i] * values[i + 1] > 0
        if same_sign and y1 >= y0 and y1 > y2 and times[i] > crossings[0]:
            curvature = y0 - 2 * y1 + y2
            shift = 0.5 * (y0 - y2) / curvature if curvature else 0.0
            peaks.append((times[i] + shift * (times[i + 1] - times[i]),
                          y1 - 0.25 * (y0 - y2) * shift))
    if len(peaks) < 2:
        fail("Too few peaks to measure the damping")
    slope, _ = linear_fit([p[0] for p in peaks], [math.log(p[1]) for p in peaks])
    decay = -slope
    period = 2 * math.pi / omega
    return {
        "omega": omega,
        "amplitude": peaks[0][1],
        "decay_rate": decay,
        "damping_ratio": decay / math.hypot(decay, omega),
        "loss_per_period": 1 - math.exp(-decay * period),
    }


def coupling_iterations(case: Path) -> tuple[float, int]:
    path = case / RESIDUALS
    if not path.is_file():
        return math.nan, 0
    per_step: dict[str, int] = {}
    for line in path.read_text(errors="replace").splitlines()[1:]:
        fields = line.split()
        if len(fields) >= 2:
            per_step[fields[0]] = max(per_step.get(fields[0], 0), int(fields[1]))
    if not per_step:
        return math.nan, 0
    counts = list(per_step.values())
    return sum(counts) / len(counts), max(counts)


def execution_time(case: Path) -> float:
    matches = re.findall(r"^ExecutionTime = ([0-9.eE+-]+) s",
                         (case / "log.solids4Foam").read_text(errors="replace"),
                         re.MULTILINE)
    return float(matches[-1]) if matches else math.nan


def analyse(spec: dict) -> dict:
    case = WORK_ROOT / spec["name"]
    times, values = read_histories(case, spec)
    row = dict(spec)
    row.update(frequency_and_damping(times, values, spec["periods"]))
    row["error"] = row["omega"] / spec["omega_exact"] - 1
    row["mean_iterations"], row["max_iterations"] = coupling_iterations(case)
    row["execution_time"] = execution_time(case)
    return row


# ---------------------------------------------------------------------------
# Study definition
# ---------------------------------------------------------------------------

def build_specs(args: argparse.Namespace, reference: dict) -> list[dict]:
    exact = reference["exact"]
    study = reference["study"]
    levels = args.levels.split(",") if args.levels else list(reference["levels"])
    for level in levels:
        if level not in reference["levels"]:
            fail(f"Unknown level '{level}'; choose from {list(reference['levels'])}")
    if args.quick:
        quick = study["quick"]
        mesh_factors, time_steps = quick["meshFactors"], []
        steps, periods = quick["stepsPerPeriod"], quick["periods"]
        levels = [level for level in levels if level in quick["levels"]] \
            or quick["levels"]
        studies = {"main"}
    else:
        mesh_factors = study["meshFactors"]
        time_steps = study["timeSteps"]
        steps, periods = study["stepsPerPeriod"], study["periods"]
        studies = {"main", "solid", "coupling"} if args.study == "all" \
            else {args.study}

    specs: dict[str, dict] = {}

    def add(kind: str, solid: str, factor: int, n: int, level: str = "",
            coupling: str = "iqnils", group: str = "main") -> None:
        omega = exact["dry"]["omega"] if kind == "dry" \
            else exact["levels"][level]["omega"]
        spec = {"kind": kind, "level": level if kind == "wet" else "",
                "coupling": coupling if kind == "wet" else "",
                "solid": solid, "factor": factor, "steps": n,
                "periods": periods, "omega_exact": omega,
                "period": 2 * math.pi / omega}
        spec["name"] = case_name(spec)
        entry = specs.setdefault(spec["name"], spec)
        entry.setdefault("groups", set()).add(group)

    if "main" in studies:
        for factor in mesh_factors:
            add("dry", "highOrder", factor, steps)
            for level in levels:
                add("wet", "highOrder", factor, steps, level)
        for n in time_steps:
            add("dry", "highOrder", study["timeStudyFactor"], n)
            for level in levels:
                add("wet", "highOrder", study["timeStudyFactor"], n, level)
    if "solid" in studies:
        for factor in mesh_factors:
            add("dry", "standard", factor, steps, group="solid")
            for level in levels:
                add("wet", "standard", factor, steps, level, group="solid")
            add("dry", "highOrder", factor, steps, group="solid")
            for level in levels:
                add("wet", "highOrder", factor, steps, level, group="solid")
    if "coupling" in studies:
        factor = study["couplingStudyFactor"]
        add("dry", "highOrder", factor, steps, group="coupling")
        for level in levels:
            for coupling in ("iqnils", "robin"):
                add("wet", "highOrder", factor, steps, level, coupling,
                    group="coupling")
    for spec in specs.values():
        spec["groups"] = sorted(spec["groups"])
    return list(specs.values())


# ---------------------------------------------------------------------------
# Checks and reporting
# ---------------------------------------------------------------------------

def observed_order(values: list[float], ratio: float = 2.0) -> float:
    """Order from three values at a constant refinement ratio."""
    d1, d2 = values[0] - values[1], values[1] - values[2]
    if d1 == 0 or d2 == 0 or d1 * d2 < 0:
        return math.nan
    return math.log(abs(d1 / d2)) / math.log(ratio)


def find(rows: list[dict], **keys) -> dict | None:
    for row in rows:
        if all(row.get(k) == v for k, v in keys.items()):
            return row
    return None


def add_ratios(rows: list[dict], reference: dict) -> None:
    exact = reference["exact"]["levels"]
    for row in rows:
        if row["kind"] != "wet":
            continue
        dry = find(rows, kind="dry", solid=row["solid"], factor=row["factor"],
                   steps=row["steps"], periods=row["periods"])
        if dry is None:
            continue
        row["ratio"] = row["omega"] / dry["omega"]
        row["ratio_error"] = row["ratio"] / exact[row["level"]]["ratio"] - 1
        row["ratio_thin_error"] = (
            row["ratio"] / exact[row["level"]]["ratioThinRing"] - 1
        )


def pct(value: float) -> str:
    return "–" if value is None or not math.isfinite(value) else f"{100 * value:+.3f}%"


def num(value: float, fmt: str = ".5f") -> str:
    return "–" if value is None or not math.isfinite(value) else format(value, fmt)


def check_rows(rows: list[dict], reference: dict, args: argparse.Namespace,
               lines: list[str]) -> list[str]:
    tol = reference["tolerances"]
    study = reference["study"]
    failures: list[str] = []
    levels = sorted({r["level"] for r in rows if r["kind"] == "wet"},
                    key=list(reference["levels"]).index)
    orders = ["", "## Observed orders", "",
              "| Series | Values | Order |", "|---|---|---:|"]

    def check(condition: bool, message: str) -> None:
        lines.append(f"- {'PASS' if condition else 'FAIL'}: {message}")
        if not condition:
            failures.append(message)

    def record(series: str, values: list[float]) -> float:
        order = observed_order(values)
        orders.append(f"| {series} | {', '.join(f'{v:.6g}' for v in values)} "
                      f"| {num(order, '.2f')} |")
        return order

    for row in rows:
        if row["loss_per_period"] < -tol["maxGrowthPerPeriod"]:
            check(False, f"{row['name']}: the amplitude grows by "
                  f"{pct(-row['loss_per_period'])} per period")

    if args.quick:
        quick = tol["quick"]
        for row in rows:
            check(abs(row["error"]) <= quick["omega"],
                  f"{row['name']}: frequency error {pct(row['error'])} within "
                  f"{100 * quick['omega']:.1f}%")
        return failures

    series_keys = [("dry", {"kind": "dry"})] + [
        (level, {"kind": "wet", "level": level, "coupling": "iqnils"})
        for level in levels
    ]
    factors = study["meshFactors"]
    steps = study["stepsPerPeriod"]

    main = [r for r in rows if "main" in r["groups"]]
    for label, keys in series_keys if main else []:
        series = [find(main, solid="highOrder", factor=f, steps=steps, **keys)
                  for f in factors]
        if any(s is None for s in series):
            continue
        finest = series[-1]
        check(abs(finest["error"]) <= tol["omega"],
              f"{label}: finest-mesh frequency error {pct(finest['error'])} "
              f"within {100 * tol['omega']:.2f}%")
        # The high-order solid is converged in space on the coarsest mesh,
        # so the mesh changes are at the level of the measurement noise and
        # have no meaningful order; they must stay small
        omegas = [s["omega"] for s in series]
        record(f"{label}: frequency, high-order solid, mesh", omegas)
        change = max(abs(omegas[i + 1] / omegas[i] - 1)
                     for i in range(len(omegas) - 1))
        check(change <= tol["meshChange"],
              f"{label}: largest mesh change in the frequency "
              f"{100 * change:.3f}% within {100 * tol['meshChange']:.2f}%")
        if label != "dry":
            ratios = [s["ratio_error"] for s in series]
            order = record(f"{label}: wet/dry ratio error, mesh", ratios)
            check(abs(finest["ratio_error"]) <= tol["ratio"],
                  f"{label}: finest-mesh wet/dry ratio error "
                  f"{pct(finest['ratio_error'])} within "
                  f"{100 * tol['ratio']:.2f}%")
            check(abs(ratios[-1]) < abs(ratios[0]),
                  f"{label}: the wet/dry ratio error decreases with mesh "
                  f"refinement ({pct(ratios[0])} to {pct(ratios[-1])})")
            check(abs(finest["ratio_thin_error"]) <= tol["ratioThinRing"],
                  f"{label}: finest-mesh ratio against thin-ring theory "
                  f"{pct(finest['ratio_thin_error'])} within "
                  f"{100 * tol['ratioThinRing']:.2f}%")
        time_series = [find(main, solid="highOrder",
                            factor=study["timeStudyFactor"], steps=n, **keys)
                       for n in study["timeSteps"]]
        if any(s is None for s in time_series):
            continue
        omegas = [s["omega"] for s in time_series]
        order = record(f"{label}: frequency, time step", omegas)
        check(math.isfinite(order) and order >= tol["minTimeOrder"],
              f"{label}: observed time order {num(order, '.2f')} at least "
              f"{tol['minTimeOrder']}")
        # Second-order Richardson extrapolation from the two smallest steps
        extrapolated = omegas[-1] + (omegas[-1] - omegas[-2]) / 3
        error = extrapolated / time_series[-1]["omega_exact"] - 1
        lines.append(f"  - {label}: time-extrapolated frequency "
                     f"{extrapolated:.6f} rad/s, error {pct(error)}")
        check(abs(error) <= tol["omegaExtrapolated"],
              f"{label}: time-extrapolated frequency error {pct(error)} "
              f"within {100 * tol['omegaExtrapolated']:.2f}%")
        loss = time_series[-1]["loss_per_period"]
        check(-tol["maxGrowthPerPeriod"] <= loss <= tol["maxLossPerPeriod"],
              f"{label}: amplitude loss {pct(loss)} per period at "
              f"{time_series[-1]['steps']} steps per period between "
              f"{-100 * tol['maxGrowthPerPeriod']:.1f}% and "
              f"{100 * tol['maxLossPerPeriod']:.1f}%")

    solid_rows = [r for r in rows if "solid" in r["groups"]]
    for label, keys in series_keys if solid_rows else []:
        series = [find(solid_rows, solid="standard", factor=f, steps=steps,
                       **keys) for f in factors]
        if any(s is None for s in series):
            continue
        order = record(f"{label}: frequency, standard solid, mesh",
                       [s["omega"] for s in series])
        check(math.isfinite(order) and order >= tol["minMeshOrder"],
              f"{label}: standard-solid observed mesh order "
              f"{num(order, '.2f')} at least {tol['minMeshOrder']}")
        if label != "dry":
            finest = series[-1]
            check(abs(finest["ratio_error"]) <= tol["ratio"],
                  f"{label}: standard-solid finest-mesh wet/dry ratio error "
                  f"{pct(finest['ratio_error'])} within "
                  f"{100 * tol['ratio']:.2f}% (frequency error "
                  f"{pct(finest['error'])})")

    coupling_rows = [r for r in rows if "coupling" in r["groups"]]
    for level in levels if coupling_rows else []:
        iq = find(coupling_rows, kind="wet", level=level, coupling="iqnils")
        rb = find(coupling_rows, kind="wet", level=level, coupling="robin")
        if iq is None or rb is None:
            continue
        check(abs(rb["omega"] / iq["omega"] - 1) <= tol["couplingAgreement"],
              f"{level}: Robin and IQN-ILS frequencies agree to "
              f"{pct(rb['omega'] / iq['omega'] - 1)} (within "
              f"{100 * tol['couplingAgreement']:.2f}%); mean coupling "
              f"iterations per step {num(iq['mean_iterations'], '.2f')} "
              f"(IQN-ILS) and {num(rb['mean_iterations'], '.2f')} (Robin)")
    if len(orders) > 5:
        lines += orders
    return failures


def table(rows: list[dict]) -> list[str]:
    out = [
        "| Case | ω (rad/s) | Exact | Error | Ratio | Ratio error | "
        "Thin-ring ratio error | Loss/period | Iter./step | Time (s) |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        out.append(
            f"| {r['name']} | {num(r['omega'])} | {num(r['omega_exact'])} | "
            f"{pct(r['error'])} | {num(r.get('ratio', math.nan))} | "
            f"{pct(r.get('ratio_error', math.nan))} | "
            f"{pct(r.get('ratio_thin_error', math.nan))} | "
            f"{pct(r['loss_per_period'])} | "
            f"{num(r['mean_iterations'], '.2f')} | "
            f"{num(r['execution_time'], '.0f')} |"
        )
    return out


def write_csv(path: Path, rows: list[dict]) -> None:
    fields = ["name", "kind", "level", "coupling", "solid", "factor", "steps",
              "periods", "omega", "omega_exact", "error", "ratio",
              "ratio_error", "ratio_thin_error", "amplitude", "decay_rate",
              "damping_ratio", "loss_per_period", "mean_iterations",
              "max_iterations", "execution_time"]
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--study", choices=("all", "main", "solid", "coupling"),
                        default="all",
                        help="main: high-order solid mesh and time-step studies; "
                        "solid: standard against high-order solid; coupling: "
                        "IQN-ILS against Robin-Neumann (default: all)")
    parser.add_argument("--levels",
                        help="comma-separated added-mass levels (default: all)")
    parser.add_argument("--cores", type=int, default=1,
                        help="number of serial cases run at the same time")
    parser.add_argument("--reuse", action="store_true",
                        help="reuse completed runs under verification/work whose "
                        "settings match")
    parser.add_argument("--quick", action="store_true",
                        help="short smoke run on the coarsest mesh")
    args = parser.parse_args()
    if args.cores < 1:
        parser.error("--cores must be a positive integer")
    for executable in ("blockMesh", "solids4Foam"):
        if shutil.which(executable) is None:
            fail(f"Required executable '{executable}' is unavailable. "
                 "Source OpenFOAM and build solids4foam first.")
    reference = json.loads(REFERENCE_FILE.read_text())
    specs = build_specs(args, reference)
    WORK_ROOT.mkdir(parents=True, exist_ok=True)
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    print(f"Running {len(specs)} cases, {args.cores} at a time")
    errors = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.cores) as pool:
        futures = {pool.submit(run_case, spec, reference, args.reuse): spec
                   for spec in specs}
        for future in concurrent.futures.as_completed(futures):
            try:
                print(future.result(), flush=True)
            except RuntimeError as error:
                errors.append(str(error))
                print(f"ERROR: {error}", flush=True)

    rows = []
    for spec in specs:
        try:
            rows.append(analyse(spec))
        except RuntimeError as error:
            if not any(spec["name"] in e for e in errors):
                errors.append(f"{spec['name']}: {error}")
    add_ratios(rows, reference)
    rows.sort(key=lambda r: (r["kind"] != "dry",
                             list(reference["levels"]).index(r["level"])
                             if r["level"] else -1,
                             r["coupling"], r["solid"], r["factor"], r["steps"]))

    lines = ["# ringAddedMass verification summary", ""]
    lines += table(rows)
    lines += ["", "## Checks", ""]
    failures = check_rows(rows, reference, args, lines)
    for error in errors:
        lines.append(f"- FAIL: {error}")
    failures += errors
    lines += ["", "PASSED" if not failures else f"FAILED ({len(failures)} checks)"]
    summary = OUTPUT_ROOT / "verification_summary.md"
    summary.write_text("\n".join(lines) + "\n")
    write_csv(OUTPUT_ROOT / "ringAddedMass_results.csv", rows)
    print("\n".join(lines))
    print(f"\nWrote {summary}")
    return 0 if not failures else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (RuntimeError, subprocess.SubprocessError, OSError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        sys.exit(2)
