#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -rf system/*Subset constant/*Subset VTK postProcessing/ case.foam \
        constant/polyMesh \
        mechanicalProperties.withDefaultValues \
        solidProperties.withDefaultValues *.png

# Restore the stored case format
solids4Foam::restoreCaseFormat .

# Remove the regression test cases, and the verification study cases and
# results, too with ./Allclean all
if [ "${1:-}" = "all" ]
then
    rm -rf regressionTests
    (cd verification && ./Allclean)
fi
