#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -rf system/*Subset constant/*Subset VTK postProcessing/ case.foam \
        mechanicalProperties.withDefaultValues \
        solidProperties.withDefaultValues *.png

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
