#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
cleanCase fluid
cleanCase solid
if [[ $WM_PROJECT == "foam" ]]
then
    foamClearPolyMesh -region fluid
    foamClearPolyMesh -region solid
else
    foamCleanPolyMesh -region fluid
    foamCleanPolyMesh -region solid
fi
\rm -rf system/meshDict constant/solid/polyMesh constant/fluid/polyMesh
\rm -rf case.foam residuals

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
