#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create the mesh
#m4 constant/polyMesh/blockMeshDictAxi.m4 > constant/polyMesh/blockMeshDict &> log.m4.blockMesh
solids4Foam::runApplication blockMesh

# Run the solver
solids4Foam::runApplication solids4Foam

# Create plots
if command -v gnuplot &> /dev/null
then
    echo "Generating stressVsStrain.png using gnuplot"
    gnuplot plot.gnuplot &> /dev/null
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
