#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf postProcessing
rm -rf 'history'
rm -r processor*
rm -f *.log
rm -f *.dat
rm -f *.foam
rm -f *.eps
rm log.*
rm -r constant/polyMesh
