#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

solids4Foam::caseOnlyRunsWithFoamExtend

# Create the mesh
runApplication blockMesh

# Assign the water region in the alpha field
runApplication setFields

# Run the solver
runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

