#!/bin/bash

. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [[ $WM_PROJECT != "foam" ]]
then
    echo; echo "This case currently only runs in foam-extend"; echo
    exit 0
fi

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

set -e

# reset

#paraview file
touch case.foam

gzip -d ventricle_ideal_coarse.msh.gz
runApplication fluent3DMeshToFoam ventricle_ideal_coarse.msh
gzip ventricle_ideal_coarse.msh


runApplication createPatch -overwrite

# run
runApplication solids4Foam
