#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make links (serial)
./makeSerialLinks fluid solid

# Make links (parallel)
#./makeLink fluid solid

(cd fluid && ./Allrun)

# ----------------------------------------------------------------- end-of-file

