#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Run solver in serial
runApplication solids4Foam

# Run solver in parallel
#runApplication decomposePar
#runParallel solidFoam 8
#runApplication reconstructPar
