#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
cleanCase fluid
cleanCase solid
if [[ $WM_PROJECT == "foam" ]]
then
    foamClearPolyMesh -region fluid
    foamClearPolyMesh -region solid
else
    foamCleanPolyMesh -region fluid
    foamCleanPolyMesh -region solid
fi
\rm -rf history constant/solid/polyMesh/boundary
\rm -rf constant/solid/polyMesh/[c-z]*
\rm -rf case.foam

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
