#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

if [ "$WM_PROJECT" == "foam" ]
then
    if (( $(echo "$WM_PROJECT_VERSION < 4.1" |bc -l) ))
    then
        echo "Tutorial not compatible with this version of OpenFOAM"
        exit 0
    fi
else
    echo; echo "This case currently only runs in foam-extend"; echo
    exit 0
fi

# Check case version is correct
solids4Foam::convertCaseFormat .

# Cerate solid mesh
runApplication -l log.blockMesh.solid blockMesh -region solid

# Create fluid mesh
# fluentMeshToFoam does not have a region option so we need to workaround
# it
mkdir constant/fluid/polyMesh
runApplication fluentMeshToFoam -writeZones -writeSets beamInCrossFlow.msh
\mv constant/polyMesh/* constant/fluid/polyMesh/
cp ./constant/fluid/boundary ./constant/fluid/polyMesh

runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

