#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create the mesh
runApplication blockMesh

# Create the material cell zones
runApplication setSet -batch batch.setSet
runApplication setsToZones -noFlipMap

# Run the solver
runApplication solids4Foam

# Write contact fields for visualisation
runApplication contactFields