#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

solids4Foam::caseDoesNotRunWithFoamExtend
solids4Foam::caseDoesNotRunWithOpenFOAMOrg

wclean initialiseTaylorGreenVortex
(cd src && ./Allwclean)
cleanCase0
rm -rf constant/polyMesh dynamicCode

# Remove the regression test cases too with ./Allclean all
if [ "${1:-}" = "all" ]
then
    rm -rf regressionTests
fi
