#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Build the utility for initialising the solution
wmake initialiseTaylorGreenVortex

# Build boundary condition and mesh motion libraries
(cd src && ./Allwmake)

# Copy 0.orig to 0
restore0Dir

# Create the mesh
runApplication blockMesh

# Initialie the velocity and pressure initial fields with the analytical
# solutions
runApplication initialiseTaylorGreenVortex

# Run the solver
runApplication solids4Foam
