#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cp constant/polyMesh/blockMeshDict system/
cleanCase
mkdir constant/polyMesh ; mv -f system/blockMeshDict constant/polyMesh/
rm -f constant/polyMesh/boundary case.foam
