#!/bin/bash
set -Eeuo pipefail
IFS=$'\n\t'

# Source tutorial clean functions
export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH:-}"
: "${FOAM_LD_LIBRARY_PATH:=}"
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

# Source solids4Foam scripts
source solids4FoamScripts.sh

wclean lib src

[ -f constant/polyMesh/blockMeshDict ] && cp constant/polyMesh/blockMeshDict system/
cleanCase
[ -f system/blockMeshDict ] && mkdir constant/polyMesh && cp system/blockMeshDict constant/polyMesh/

\rm -f constant/polyMesh/boundary case.foam postProcessing.gplt
\rm -rf system/*Subset constant/*Subset postProcessing

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .

# Link files back to default solid model settings
for file in $(find ./constant ./system -name '*.segregated')
do
    ln -vnsf ${file##*/} ${file%.*}
done
