#!/bin/bash
set -Eeuo pipefail
IFS=$'\n\t'

# Source tutorial clean functions
export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH:-}"
: "${FOAM_LD_LIBRARY_PATH:=}"
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

# Source solids4Foam scripts
source solids4FoamScripts.sh

wclean lib src

cleanCase

\rm -f constant/polyMesh/boundary case.foam postProcessing.gplt
\rm -rf system/*Subset constant/*Subset postProcessing

# Restore the stored case format
solids4Foam::restoreCaseFormat .

# Link files back to default solid model settings
for file in $(find ./constant ./system -name '*.segregated')
do
    ln -vnsf ${file##*/} ${file%.*}
done
