#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf *.log case.foam constant/polyMesh postProcessing energies.dat

# Remove the regression test cases too with ./Allclean all
if [ "${1:-}" = "all" ]
then
    rm -rf regressionTests
fi
