#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# This case requires PETSc to be installed
solids4Foam::requirePetscOrExitSilently

# Check case version is correct
solids4Foam::convertCaseFormat .

# Case only runs with OpenFOAM.com
solids4Foam::caseDoesNotRunWithFoamExtend
solids4Foam::caseDoesNotRunWithOpenFOAMOrg

if ! command -v cartesianMesh &> /dev/null
then
    echo
    echo "cartesianMesh command not found, which is required for this case"
    echo
    exit 0
fi

# Create mesh
solids4Foam::runApplication cartesianMesh

# Create patches
solids4Foam::runApplication surfaceToPatch base.stl -noFunctionObjects
rm -rf constant/polyMesh; mv 0.01/polyMesh constant/; rm -rf 0.01

# Run solver
if [[ "$1" == "parallel" ]]; then
    # Run parallel
    solids4Foam::runApplication decomposePar
    solids4Foam::runParallel solids4Foam
    solids4Foam::runApplication reconstructPar
else
    # Run serial
    solids4Foam::runApplication solids4Foam
fi
