#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if ! command -v cartesianMesh &> /dev/null
then
    echo
    echo "cartesianMesh command not found, which is required for this case"
    echo
    exit 0
fi

# Create mesh
solids4Foam::runApplication cartesianMesh

# Create patches
solids4Foam::runApplication surfaceToPatch base.stl -noFunctionObjects
rm -rf constant/polyMesh; mv 0.01/polyMesh constant/; rm -rf 0.01

# Run solver
solids4Foam::runApplication solids4Foam
