#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication splitMeshRegions -cellZonesOnly -overwrite

runApplication topoSet -region gas

paraFoam -region gas -touch
paraFoam -region solid -touch

runApplication decomposePar -allRegions

runParallel $(getApplication)

#runApplication reconstructPar -allRegions -newTimes
runApplication reconstructPar -region solid -newTimes

#------------------------------------------------------------------------------
