#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

solids4Foam::caseDoesNotRunWithOpenFOAMOrg

# Version specific changes
# Note: 0/fluid/U is not converted by solids4Foam::convertCaseFormat, which only
# checks files named p
if [[ $WM_PROJECT == "foam" ]]
then
    echo "foam extend specific change"
    echo "0/fluid/U: change uniformFixedValue to timeVaryingUniformFixedValue"

    # Comment uniformFixedValue
    sed -i 's|^\([[:space:]]*type[[:space:]].*uniformFixedValue;\)|//\1|' 0/fluid/U

    # Uncomment timeVaryingUniformFixedValue
    sed -i 's|^//\([[:space:]]*type[[:space:]].*timeVaryingUniformFixedValue;\)|\1|' 0/fluid/U
fi

# Create the mesh
solids4Foam::runApplication -s solid blockMesh -region solid
solids4Foam::runApplication -s fluid blockMesh -region fluid

# Run the solver
solids4Foam::runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

