################################################################################
# Dockerfile to build solids4foam with OpenFOAM-v2412
# philip.cardiff@ucd.ie, January 2026
################################################################################

# Set the base image
FROM philippic/openfoam-v2412:ubuntu-22.04-petsc-no-openmp-system-blas

# File Author / Maintainer
LABEL maintainer="Philip Cardiff <philip.cardiff@ucd.ie>"

# Change default shell to bash
SHELL ["/bin/bash", "-c"]

# Add solids4Foam
COPY . /usr/lib/solids4foam

# Compile solids4Foam
RUN source /usr/lib/openfoam/openfoam2412/etc/bashrc && \
    cd /usr/lib/solids4foam && \
    ./Allwmake -j -s

# Clean log files
RUN cd /usr/lib/solids4foam && \
    find . -name log.* | xargs rm