################################################################################
# Dockerfile to build solids4foam with OpenFOAM-9
# philip.cardiff@ucd.ie, January 2026
################################################################################

# Set the base image
FROM philippic/openfoam-9:ubuntu20.04-petsc-no-openmp-system-blas

# File Author / Maintainer
LABEL maintainer="Philip Cardiff <philip.cardiff@ucd.ie>"

# Change default shell to bash
SHELL ["/bin/bash", "-c"]

# Add solids4Foam
COPY . /opt/solids4foam

# Compile solids4Foam
RUN source /opt/openfoam9/etc/bashrc && \
    cd /opt/solids4foam && \
    ./Allwmake -j -s

# Clean log files
RUN cd /opt/solids4foam && \
    find . -name log.* | xargs rm