#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

[ -f constant/solid/polyMesh/blockMeshDict ] && cp constant/solid/polyMesh/blockMeshDict system/solid/
[ -f constant/fluid/polyMesh/blockMeshDict ] && cp constant/fluid/polyMesh/blockMeshDict system/fluid
cleanCase
if [[ $WM_PROJECT = "foam" ]]; then
    foamClearPolyMesh -region fluid
    foamClearPolyMesh -region solid
elif [[ $WM_PROJECT_VERSION == v* ]]; then
    foamCleanPolyMesh -region fluid
    foamCleanPolyMesh -region solid
fi
[ -f system/solid/blockMeshDict ] && mkdir constant/solid/polyMesh && cp system/solid/blockMeshDict constant/solid/polyMesh/
[ -f system/fluid/blockMeshDict ] && mkdir constant/fluid/polyMesh && cp system/fluid/blockMeshDict constant/fluid/polyMesh/

rm -rf case.foam residuals force.pdf deflection.pdf postProcessing 0/fluid/velocityInletProfile

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
