#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
# source solids4FoamScripts.sh

cleanCase
foamCleanPolyMesh -region fluid
foamCleanPolyMesh -region solid
rm -rf case.foam residuals force.pdf deflection.pdf postProcessing

# Convert case version to FOAM EXTEND
# solids4Foam::convertCaseFormatFoamExtend .
