#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

#cleanCase
cleanTimeDirectories
#\rm -f constant/polyMesh/boundary
\rm case.foam
\rm -rf 0
\rm -rf processor*
\rm -f *.eps
\rm -f *.ps
\rm -rf history
\rm -rf VTK
\rm -rf forces
\rm -rf postProcessing
\rm -f log.transformPoints
\rm -f *.dat
