#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

if [ "$WM_PROJECT" = "OpenFOAM" ]
then
    # Parse arguments for library compilation
    . $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
fi

wmake libso
