/*---------------------------------------------------------------------------*\
License
    This file is part of solids4foam.

    solids4foam is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation, either version 3 of the License, or (at your
    option) any later version.

    solids4foam is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with solids4foam.  If not, see <http://www.gnu.org/licenses/>.

Class
    minEdgeLength

Description
    Return the minimum edge length of the given mesh.

Author
    Philip Cardiff, UCD.

SourceFiles
    minEdgeLength.C

\*---------------------------------------------------------------------------*/

#ifndef minEdgeLength_H
#define minEdgeLength_H

#include "polyMesh.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

    // Return minimum edge length of the given mesh
    scalar minEdgeLength(const polyMesh& mesh);

    // Return minimum edge length of the given mesh, where the given point
    // displacement field is added to the mesh point field
    scalar minEdgeLength(const polyMesh& mesh, const vectorField& pointD);

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
