#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .

# Check OpenFOAM version (tested only with fe41)
solids4Foam::caseOnlyRunsWithFoamExtend

# Create mesh
solids4Foam::runApplication blockMesh

# Run solver
solids4Foam::runApplication solids4Foam
