#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

wclean lib src

cleanCase
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam postProcessing *.png
\rm -rf system/*Subset

# Restore the stored case format
solids4Foam::restoreCaseFormat .

# Link files back to default solid model settings
for file in $(find ./0 ./constant ./system -name '*.segregated')
do
    ln -vnsf ${file##*/} ${file%.*}
done
