#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::caseDoesNotRunWithFoamExtend
solids4Foam::caseDoesNotRunWithOpenFOAMOrg

cleanCase
cleanCase fluid
cleanCase solid
rm -rf case.foam *.pdf 0/fluid/alpha.water
\cp 0/fluid/alpha.water.org 0/fluid/alpha.water
