#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# PETSc is required for this case
if [[ -z "${PETSC_DIR:-}" ]]
then
    echo; echo "Skipping this case as PETSc is not installed"
    echo "Please set the PETSC_DIR variable and rebuild solids4foam"; echo
    exit 0
fi

# Check case version is correct
solids4Foam::caseDoesNotRunWithFoamExtend
solids4Foam::caseDoesNotRunWithOpenFOAMOrg

# Create meshes
solids4Foam::runApplication -s solid blockMesh -region solid -dict system/solid/blockMeshDict.1
solids4Foam::runApplication -s fluid blockMesh -region fluid -dict system/fluid/blockMeshDict.1

# Set water volume fraction field (alpha) in the fluid
\cp 0/fluid/org/alpha.water 0/fluid/alpha.water
solids4Foam::runApplication setFields -region fluid

# Run solver
solids4Foam::runApplication solids4Foam

# Create plots
if command -v gnuplot &> /dev/null
then
    echo "Generating displacement.pdf"
    gnuplot -p displacement.gnuplot &> /dev/null

    echo "Generating iterations.pdf"
    gnuplot -p iterations.gnuplot &> /dev/null
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
