#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

# Parse arguments for library compilation
if [ -f "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments ]
then
    . "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments
fi

(cd blockCoupledSolids4FoamTools && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)

if [[ -z "${S4F_NO_RBF:-}" ]]
then
    (cd RBFMeshMotionSolver && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
else
    echo; echo "The S4F_NO_RBF variable is set: skipping RBFMeshMotionSolver"
    echo "The RBFMeshMotionSolver mesh motion solver and the rbf"
    echo "interfaceToInterfaceMapping will not be available"; echo
fi

(cd solids4FoamModels && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)

# The immersed boundary method is currently only implemented for OpenFOAM.com
if [[ "$WM_PROJECT" == "OpenFOAM" && $WM_PROJECT_VERSION == v* ]]
then
    (cd immersedBoundary && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
else
    echo; echo "Skipping immersedBoundary: it requires OpenFOAM.com"; echo
fi

#------------------------------------------------------------------------------
