#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

targetType=""

# Parse arguments for library compilation
if [ -f "$WM_PROJECT"/wmake/scripts/AllwmakeParseArguments ]
then  . "$WM_PROJECT"/wmake/scripts/AllwmakeParseArguments
fi

(cd blockCoupledSolids4FoamTools && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
(cd RBFMeshMotionSolver && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
(cd solids4FoamModels && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)

if [[ ! -z "${S4F_USE_GFORTRAN+x}" ]]
then
    (cd abaqusUMATs && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
else
    echo; echo "The S4F_USE_GFORTRAN variable is not set: skipping abaqusUMATs"
    echo "To use abaqusUMATs, install gfortran and set the S4F_USE_GFORTRAN "
    echo "variable to 1"; echo
fi

#------------------------------------------------------------------------------
