#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

# Parse arguments for library compilation
if [ -f "$WM_PROJECT"/wmake/scripts/AllwmakeParseArguments ]
then  . "$WM_PROJECT"/wmake/scripts/AllwmakeParseArguments
fi

if [ "$WM_PROJECT" = "foam" ]
then
    if [[ ! -f Make/files ]]
    then
        echo "Linking Make/files.foamextend to Make/files"
        (cd Make && ln -s files.foamextend files)
    elif [ $(readlink Make/files) != "files.foamextend" ]
    then
        echo "Updating Make/files link to Make/files.foamextend"
        (cd Make && ln -sf files.foamextend files)
    fi
else
    if [[ ! -f Make/files ]]
    then
        echo "Linking Make/files.openfoam to Make/files"
        (cd Make && ln -sf files.openfoam files)
    elif [ $(readlink Make/files) != "files.openfoam" ]
    then
        echo "Updating Make/files link to Make/files.openfoam"
        (cd Make && ln -sf files.openfoam files)
    fi
fi

wmake libso
