#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -rf constant/polyMesh case.foam postProcessing system/*Subset \
        constant/*Subset VTK *.png constant/*.withDefaultValues

# Remove the links created by Allrun for the selected contact settings
\rm -f 0/DD system/fvSchemes system/fvSolution

# Restore the stored case format
solids4Foam::restoreCaseFormat .
