#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
rm -f constant/polyMesh/boundary case.foam
rm -rf system/*Subset postProcessing
rm -rf 0; cp -r 0.org 0

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
