#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf 0/cellToRegion history constant/polyMesh/boundary
\rm case.foam
\cp 0/org/* 0/
\rm -rf system/*Subset

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
