#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create the mesh
m4 system/blockMeshDict.cylinder.m4 > constant/polyMesh/blockMeshDict
solids4Foam::runApplication blockMesh

if [[ $WM_PROJECT != "foam" ]]
then
    # Axis edges must be manually removed
    solids4Foam::runApplication collapseEdges -overwrite
fi

# Set the initial conditions
solids4Foam::runApplication setFields

# Run the solver
solids4Foam::runApplication solids4Foam
