#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

solids4Foam::caseOnlyRunsWithFoamExtend

# Create the mesh
m4 system/blockMeshDict.cylinder.m4 > constant/polyMesh/blockMeshDict
runApplication blockMesh

# Set the initial conditions
runApplication setFields

# Run the solver
runApplication solids4Foam
