#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

# Create the mesh
runApplication blockMesh

# Run the solver in serial
runApplication solids4Foam

# Run the solver in parallel
#runApplication decomposePar
#runParallel solids4Foam 4
#runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file

