#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

solids4Foam::caseDoesNotRunWithFoamExtend
solids4Foam::caseDoesNotRunWithOpenFOAMOrg

solids4Foam::requirePetscOrExitSilently

echo
echo "Compiling libraries..."
(cd src && bash ./Allwmake -s)

# Create mesh
solids4Foam::runApplication blockMesh

# Run solver
solids4Foam::runApplication solids4Foam

# Sample the stress along a line at theta = 45 deg
solids4Foam::runApplication postProcess -func sample -latestTime

# Create plots
if command -v gnuplot &> /dev/null
then
    echo "Generating plot using gnuplot"
    gnuplot plot.gnuplot &> /dev/null
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
