#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
cleanCase fluid
cleanCase solid
rm -rf case.foam
rm 0/fluid/alpha1

# Convert case version to FOAM EXTEND
solids4Foam::convertCaseFormatFoamExtend .
