#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ ! -f "$FOAM_USER_LIBBIN/libwaves2Foam.so" ]
then
    echo "libwaves2Foam.so is required for this tutorial, but it is not found"
    echo "in $FOAM_USER_LIBBIN/libwaves2Foam.so"
    exit 0
fi

# Source solids4Foam scripts
source solids4FoamScripts.sh


# Create meshes
solids4Foam::runApplication -s solid blockMesh -region solid
solids4Foam::runApplication -s fluid blockMesh -region fluid

# Set fluid wave parameters
# As the waves2Foam utilities do not have the "-region" option, we will
# temporarily move the fluid mesh and settings to the main constant directory
# and run the waves2Foam utility and then move the fluid mesh and setting back

# Move fluid to default directory
mv constant/fluid/waveProperties.input constant/
mv constant/fluid/waveProperties constant/
mv constant/fluid/transportProperties constant/
mv constant/fluid/g constant/
mv constant/fluid/polyMesh constant/
mv 0/fluid/alpha1 0/
mv 0/fluid/U 0/
mv 0/fluid/pd 0/

# Compute the wave parameters
solids4Foam::runApplication -s fluid setWaveParameters

# Set the wave field
solids4Foam::runApplication -s fluid setWaveField

# Move fluid back to fluid sub-directory
mv constant/waveProperties.input constant/fluid/
mv constant/waveProperties constant/fluid/
mv constant/transportProperties constant/fluid/
mv constant/g constant/fluid/
mv constant/polyMesh constant/fluid/
mv 0/alpha1 0/fluid/
mv 0/U 0/fluid/
mv 0/pd 0/fluid/

# Run solver
solids4Foam::runApplication solids4Foam
