{
    Info<< "/*---------------------------------------------------------------------------*\\\n"
        << "|    For further information on the solids4Foam toolbox implementations,      |\n"
        << "|    please see the following publications:                                   |\n"
        << "|                                                                             |\n"
        << "|    P. Cardiff, A Karac, P. De Jaeger, H. Jasak, J. Nagy, A. Ivankovic,      |\n"
        << "|    Z. Tukovic: An open-source finite volume toolbox for solid mechanics and |\n"
        << "|    fluid-solid interaction simulations. arXiv:1808.10736v2, 2018, available |\n"
        << "|    at https://arxiv.org/abs/1808.10736.                                     |\n"
        << "|                                                                             |\n"
        << "|    Z. Tukovic, A. Karac, P. Cardiff, H. Jasak, A. Ivankovic: OpenFOAM       |\n"
        << "|    finite volume solver for fluid-solid interaction.  Transactions of       |\n"
        << "|    Famena, 42 (3), pp. 1-31, 2018, 10.21278/TOF.42301.                      |\n"
        << "\\*---------------------------------------------------------------------------*/"
        << nl << endl;
}
