{
    Info<< "/*---------------------------------------------------------------------------*\\\n"
        << "|    For further information on the solids4Foam toolbox implementations,      |\n"
        << "|    please see www.solids4foam.com and the following publication:            |\n"
        << "|                                                                             |\n"
        << "|    P. Cardiff, I. Batistić Ž. Tuković: solids4foam: A toolbox for           |\n"
        << "|    performing solid mechanics and fluid-solid interaction simulations in    |\n"
        << "|    OpenFOAM. Journal of Open Source Software. 2025, 10(108), 7407,          |\n"
        << "|    10.21105/joss.07407.                                                     |\n"
        << "\\*---------------------------------------------------------------------------*/"
        << nl << endl;
}
