{
    Info<< "/*---------------------------------------------------------------------------*\\\n"
        << "|    For further information on the solids4Foam toolbox implementations,      |\n"
        << "|    please see the following publications:                                   |\n"
        << "|                                                                             |\n"
        << "|    P. Cardiff, A Karac, P. De Jaeger, H. Jasak, J. Nagy, A. Ivankovic,      |\n"
        << "|    Z. Tukovic: An open-source finite volume toolbox for solid mechanics and |\n"
        << "|    fluid-solid interaction simulations. Computer Programs in Physics,       |\n"
        << "|    Computer Physics Communications, 2017, Under review.                     |\n"
        << "|                                                                             |\n"
        << "|    Z. Tukovic, A. Karac, P. Cardiff, H. Jasak, A. Ivankovic: Parallel       |\n"
        << "|    unstructured finite-volume method for fluid-structure interaction in     |\n"
        << "|    OpenFOAM. Transaction of FAMENA, 2016, Under review.                     |\n"
        << "\\*---------------------------------------------------------------------------*/"
        << nl << endl;
}
