#!/bin/bash

. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"
source solids4FoamScripts.sh

wclean lib src
cleanCase
rm -f gmsh/*.msh
solids4Foam::restoreCaseFormat .

for file in constant/solidProperties.segregated \
            system/fvSolution.segregated
do
    ln -vnsf "${file##*/}" "${file%.*}"
done

# Remove the regression test cases, and the verification study cases and
# results, too with ./Allclean all
if [ "${1:-}" = "all" ]
then
    rm -rf regressionTests
    (cd verification && ./Allclean)
fi
