#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
cleanCase fluid
cleanCase solid
(cd constant/solid/polyMesh && find . ! -name 'blockMeshDict' -type f -exec rm -f {} +)
(cd constant/fluid/polyMesh && find . ! -name 'blockMeshDict' -type f -exec rm -f {} +)
rm -rf case.foam residuals force.pdf deflection.pdf postProcessing

# Restore the stored FSI3 dictionaries if an Allrun benchmark run was
# interrupted before it could restore them: every backup found, so that a
# file added to the Allrun list cannot leave a backup that blocks the next run
while IFS= read -r -d '' file
do
    mv -f "${file}" "${file%.stored}"
done < <(find 0 constant system -name '*.stored' -print0)

# Restore the stored case format
solids4Foam::restoreCaseFormat .

# Link the default Dirichlet-Neumann IQN-ILS dictionaries, which a Robin run
# replaces; foam-extend's case conversion may also have replaced the links
ln -vnsf fsiProperties.iqnils constant/fsiProperties
ln -vnsf U.dirichletNeumann 0/fluid/U
ln -vnsf p.dirichletNeumann 0/fluid/p
