#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
m4 constant/polyMesh/blockMeshDict.thickCylinder.m4 > constant/polyMesh/blockMeshDict
runApplication blockMesh

# Run solver
runApplication solidFoam