#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

solids4Foam::caseDoesNotRunWithOpenFOAMOrg

cleanCase
\rm -rf constant/polyMesh case.foam postProcessing 0/polyMesh 0/cellToRegion
\rm -rf constant/punch_top constant/punch_bottom system/meshDict
\rm -rf system/punch_bottomSubset system/punch_topSubset
\rm -rf 0/D[x,y,z]

# Restore the stored case format
solids4Foam::restoreCaseFormat .
