#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

solids4Foam::caseOnlyRunsWithFoamExtend

if ! command -v cartesianMesh &> /dev/null
then
    echo
    echo "cartesianMesh command not found, which is required for this case"
    echo
    exit 0
fi

# Create top mesh
cp system/punch_top/meshDict system/meshDict
solids4Foam::runApplication -s punch_top cartesianMesh
mkdir constant/punch_top
mv constant/polyMesh constant/punch_top/

# Create bottom mesh
cp system/punch_bottom/meshDict system/meshDict
solids4Foam::runApplication -s punch_bottom cartesianMesh
mkdir constant/punch_bottom
mv constant/polyMesh constant/punch_bottom/

# Merge sub meshes
solids4Foam::runApplication mergeSubMeshes punch_top punch_bottom

# Scale the geometry to metres
echo "Running transformPoints"
transformPoints -scale "(0.001 0.001 0.001)" >& log.transformPoints

# Create patches
solids4Foam::runApplication autoPatch 45 -overwrite
solids4Foam::runApplication createPatch -overwrite
solids4Foam::runApplication splitPatch -overwrite

# Create cell zones needed by the mechanical law
solids4Foam::runApplication setSet -batch batch.setSet
solids4Foam::runApplication setsToZones

# Remove the sub meshes
rm -rf constant/punch_top constant/punch_bottom system/meshDict

# Run the solver
solids4Foam::runApplication solids4Foam

# ----------------------------------------------------------------- end-of-file

