#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -f constant/polyMesh/boundary case.foam tipDisplacement.png
\rm -rf system/*Subset constant/*Subset postProcessing
\rm -f constant/*.withDefaultValues

# Restore the stored case format
solids4Foam::restoreCaseFormat .

# Link files back to the default (petscSnes) solid model settings
for file in $(find ./0 ./constant ./system -name '*.petscSnes')
do
    ln -vnsf ${file##*/} ${file%.*}
done

# Restore the default time scheme and remove comparison runs
ln -vnsf fvSchemes.bdf2 system/fvSchemes
rm -rf timeSchemeRuns

# Remove the regression test cases too with ./Allclean all
if [ "${1:-}" = "all" ]
then
    rm -rf regressionTests
fi
