#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
runApplication blockMesh

# Run solver
runApplication solids4Foam

# Plot energies, if gnuplot is installed
echo "If gnuplot is installed, view plots with:"
echo "$> gnuplot plotStress.gnuplot -p"
echo "$> gnuplot plotEnergies.gnuplot -p"
#gnuplot plotStress.gnuplot -p
#gnuplot plotEnergies.gnuplot -p
