#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
solids4Foam::runApplication blockMesh

# Run solver
solids4Foam::runApplication solids4Foam

# Create plots
if command -v gnuplot &> /dev/null
then
    echo "Generating stress.pdf using gnuplot"
    gnuplot plotStress.gnuplot &> /dev/null
    echo "Generating energies.pdf using gnuplot"
    gnuplot plotEnergies.gnuplot &> /dev/null
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
