#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf constant/faMesh/faceLabels
\rm -rf constant/faMesh/faBoundary
\rm -rf dome.sMesh faMeshDefinition
\rm -rf simplySupportDomeMesh.vtk simplySupportDomeNormals.vtk
\rm -rf case.foam