#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication createFaMeshFromStlNew dome

echo "cp boundary constant/polyMesh"
\cp boundary constant/polyMesh/

runApplication extrudeMesh
runApplication makeFaMesh
runApplication checkFaMesh
runApplication solids4Foam