# Removing trailing whitespace from all files
name: Check for trailing whitespace

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  check-whitespace:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check for trailing whitespace
      run: |
        # Find files with trailing whitespace
        if git grep -I -n '[[:blank:]]\+$'
        then
          echo "❌ Trailing whitespace found in the files above. Please fix them manually."
          exit 1
        else
          echo "✅ No trailing whitespace found."
        fi
