#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cleanTimeDirectories
\rm -rf processor*
\rm -f *.eps
\rm -f *.vtk
\rm -rf history
\rm -rf VTK
\rm -rf forces
