#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ "$WM_PROJECT" = "foam" ]
then
    if (( $(echo "$WM_PROJECT_VERSION < 4.1" |bc -l) ))
    then
        echo "Tutorial not compatible with this version of OpenFOAM"
        exit 0
    fi
else
    echo; echo "This case currently only runs in foam-extend"; echo
    exit 0
fi

runApplication fluentMeshToFoam -writeZones CIC.msh
cp boundary ./constant/polyMesh

runApplication solids4Foam
