#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication fluentMeshToFoam rotateSphere.msh
runApplication changeDictionary

# Run solver
runApplication solidFoam