#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

cleanCase
\rm -f constant/polyMesh/boundary case.foam

# Restore the stored case format
solids4Foam::restoreCaseFormat .
